import { ApplicationGateway } from '../models/ApplicationGateway';
import { CloudError } from '../models/CloudError';
import { TagsObject } from '../models/TagsObject';
import { ApplicationGatewayListResult } from '../models/ApplicationGatewayListResult';
import { ApplicationGatewayBackendHealth } from '../models/ApplicationGatewayBackendHealth';
import { ApplicationGatewayOnDemandProbe } from '../models/ApplicationGatewayOnDemandProbe';
import { ApplicationGatewayBackendHealthOnDemand } from '../models/ApplicationGatewayBackendHealthOnDemand';
import { Error } from '../models/Error';
import { ApplicationGatewayAvailableWafRuleSetsResult } from '../models/ApplicationGatewayAvailableWafRuleSetsResult';
import { ApplicationGatewayAvailableSslOptions } from '../models/ApplicationGatewayAvailableSslOptions';
import { ApplicationGatewayAvailableSslPredefinedPolicies } from '../models/ApplicationGatewayAvailableSslPredefinedPolicies';
import { ApplicationGatewaySslPredefinedPolicy } from '../models/ApplicationGatewaySslPredefinedPolicy';
import { ApplicationSecurityGroup } from '../models/ApplicationSecurityGroup';
import { ApplicationSecurityGroupListResult } from '../models/ApplicationSecurityGroupListResult';
import { AvailableDelegationsResult } from '../models/AvailableDelegationsResult';
import { AvailableServiceAliasesResult } from '../models/AvailableServiceAliasesResult';
import { AzureFirewall } from '../models/AzureFirewall';
import { AzureFirewallListResult } from '../models/AzureFirewallListResult';
import { AzureFirewallFqdnTagListResult } from '../models/AzureFirewallFqdnTagListResult';
import { BastionShareableLinkListRequest } from '../models/BastionShareableLinkListRequest';
import { SessionIds } from '../models/SessionIds';
import { BastionHost } from '../models/BastionHost';
import { BastionHostListResult } from '../models/BastionHostListResult';
import { BastionShareableLinkListResult } from '../models/BastionShareableLinkListResult';
import { BastionActiveSessionListResult } from '../models/BastionActiveSessionListResult';
import { BastionSessionDeleteResult } from '../models/BastionSessionDeleteResult';
import { DnsNameAvailabilityResult } from '../models/DnsNameAvailabilityResult';
import { DdosCustomPolicy } from '../models/DdosCustomPolicy';
import { DdosProtectionPlan } from '../models/DdosProtectionPlan';
import { DdosProtectionPlanListResult } from '../models/DdosProtectionPlanListResult';
import { EndpointServicesListResult } from '../models/EndpointServicesListResult';
import { ExpressRouteCircuitAuthorization } from '../models/ExpressRouteCircuitAuthorization';
import { AuthorizationListResult } from '../models/AuthorizationListResult';
import { ExpressRouteCircuitPeering } from '../models/ExpressRouteCircuitPeering';
import { ExpressRouteCircuitPeeringListResult } from '../models/ExpressRouteCircuitPeeringListResult';
import { ExpressRouteCircuitConnection } from '../models/ExpressRouteCircuitConnection';
import { ExpressRouteCircuitConnectionListResult } from '../models/ExpressRouteCircuitConnectionListResult';
import { PeerExpressRouteCircuitConnection } from '../models/PeerExpressRouteCircuitConnection';
import { PeerExpressRouteCircuitConnectionListResult } from '../models/PeerExpressRouteCircuitConnectionListResult';
import { ExpressRouteCircuit } from '../models/ExpressRouteCircuit';
import { ExpressRouteCircuitsArpTableListResult } from '../models/ExpressRouteCircuitsArpTableListResult';
import { ExpressRouteCircuitsRoutesTableListResult } from '../models/ExpressRouteCircuitsRoutesTableListResult';
import { ExpressRouteCircuitsRoutesTableSummaryListResult } from '../models/ExpressRouteCircuitsRoutesTableSummaryListResult';
import { ExpressRouteCircuitStats } from '../models/ExpressRouteCircuitStats';
import { ExpressRouteCircuitListResult } from '../models/ExpressRouteCircuitListResult';
import { ExpressRouteServiceProviderListResult } from '../models/ExpressRouteServiceProviderListResult';
import { ExpressRouteCrossConnectionListResult } from '../models/ExpressRouteCrossConnectionListResult';
import { ExpressRouteCrossConnection } from '../models/ExpressRouteCrossConnection';
import { ExpressRouteCrossConnectionPeeringList } from '../models/ExpressRouteCrossConnectionPeeringList';
import { ExpressRouteCrossConnectionPeering } from '../models/ExpressRouteCrossConnectionPeering';
import { ExpressRouteCrossConnectionsRoutesTableSummaryListResult } from '../models/ExpressRouteCrossConnectionsRoutesTableSummaryListResult';
import { ExpressRouteGatewayList } from '../models/ExpressRouteGatewayList';
import { ExpressRouteGateway } from '../models/ExpressRouteGateway';
import { ExpressRouteConnection } from '../models/ExpressRouteConnection';
import { ExpressRouteConnectionList } from '../models/ExpressRouteConnectionList';
import { ExpressRoutePortsLocationListResult } from '../models/ExpressRoutePortsLocationListResult';
import { ExpressRoutePortsLocation } from '../models/ExpressRoutePortsLocation';
import { ExpressRoutePort } from '../models/ExpressRoutePort';
import { ExpressRoutePortListResult } from '../models/ExpressRoutePortListResult';
import { ExpressRouteLink } from '../models/ExpressRouteLink';
import { ExpressRouteLinkListResult } from '../models/ExpressRouteLinkListResult';
import { FirewallPolicy } from '../models/FirewallPolicy';
import { FirewallPolicyListResult } from '../models/FirewallPolicyListResult';
import { FirewallPolicyRuleGroup } from '../models/FirewallPolicyRuleGroup';
import { FirewallPolicyRuleGroupListResult } from '../models/FirewallPolicyRuleGroupListResult';
import { IpGroup } from '../models/IpGroup';
import { IpGroupListResult } from '../models/IpGroupListResult';
import { LoadBalancer } from '../models/LoadBalancer';
import { LoadBalancerListResult } from '../models/LoadBalancerListResult';
import { LoadBalancerBackendAddressPoolListResult } from '../models/LoadBalancerBackendAddressPoolListResult';
import { BackendAddressPool } from '../models/BackendAddressPool';
import { LoadBalancerFrontendIPConfigurationListResult } from '../models/LoadBalancerFrontendIPConfigurationListResult';
import { FrontendIPConfiguration } from '../models/FrontendIPConfiguration';
import { InboundNatRuleListResult } from '../models/InboundNatRuleListResult';
import { InboundNatRule } from '../models/InboundNatRule';
import { LoadBalancerLoadBalancingRuleListResult } from '../models/LoadBalancerLoadBalancingRuleListResult';
import { LoadBalancingRule } from '../models/LoadBalancingRule';
import { LoadBalancerOutboundRuleListResult } from '../models/LoadBalancerOutboundRuleListResult';
import { OutboundRule } from '../models/OutboundRule';
import { NetworkInterfaceListResult } from '../models/NetworkInterfaceListResult';
import { LoadBalancerProbeListResult } from '../models/LoadBalancerProbeListResult';
import { Probe } from '../models/Probe';
import { NatGateway } from '../models/NatGateway';
import { NatGatewayListResult } from '../models/NatGatewayListResult';
import { NetworkInterface } from '../models/NetworkInterface';
import { EffectiveRouteListResult } from '../models/EffectiveRouteListResult';
import { EffectiveNetworkSecurityGroupListResult } from '../models/EffectiveNetworkSecurityGroupListResult';
import { NetworkInterfaceIPConfigurationListResult } from '../models/NetworkInterfaceIPConfigurationListResult';
import { NetworkInterfaceIPConfiguration } from '../models/NetworkInterfaceIPConfiguration';
import { NetworkInterfaceLoadBalancerListResult } from '../models/NetworkInterfaceLoadBalancerListResult';
import { NetworkInterfaceTapConfiguration } from '../models/NetworkInterfaceTapConfiguration';
import { NetworkInterfaceTapConfigurationListResult } from '../models/NetworkInterfaceTapConfigurationListResult';
import { NetworkProfile } from '../models/NetworkProfile';
import { NetworkProfileListResult } from '../models/NetworkProfileListResult';
import { NetworkSecurityGroup } from '../models/NetworkSecurityGroup';
import { NetworkSecurityGroupListResult } from '../models/NetworkSecurityGroupListResult';
import { SecurityRule } from '../models/SecurityRule';
import { SecurityRuleListResult } from '../models/SecurityRuleListResult';
import { NetworkVirtualAppliance } from '../models/NetworkVirtualAppliance';
import { NetworkVirtualApplianceListResult } from '../models/NetworkVirtualApplianceListResult';
import { NetworkWatcher } from '../models/NetworkWatcher';
import { ErrorResponse } from '../models/ErrorResponse';
import { NetworkWatcherListResult } from '../models/NetworkWatcherListResult';
import { TopologyParameters } from '../models/TopologyParameters';
import { Topology } from '../models/Topology';
import { VerificationIPFlowParameters } from '../models/VerificationIPFlowParameters';
import { VerificationIPFlowResult } from '../models/VerificationIPFlowResult';
import { NextHopParameters } from '../models/NextHopParameters';
import { NextHopResult } from '../models/NextHopResult';
import { SecurityGroupViewParameters } from '../models/SecurityGroupViewParameters';
import { SecurityGroupViewResult } from '../models/SecurityGroupViewResult';
import { PacketCaptureResult } from '../models/PacketCaptureResult';
import { PacketCapture } from '../models/PacketCapture';
import { PacketCaptureQueryStatusResult } from '../models/PacketCaptureQueryStatusResult';
import { PacketCaptureListResult } from '../models/PacketCaptureListResult';
import { TroubleshootingParameters } from '../models/TroubleshootingParameters';
import { TroubleshootingResult } from '../models/TroubleshootingResult';
import { QueryTroubleshootingParameters } from '../models/QueryTroubleshootingParameters';
import { FlowLogInformation } from '../models/FlowLogInformation';
import { FlowLogStatusParameters } from '../models/FlowLogStatusParameters';
import { ConnectivityParameters } from '../models/ConnectivityParameters';
import { ConnectivityInformation } from '../models/ConnectivityInformation';
import { AzureReachabilityReportParameters } from '../models/AzureReachabilityReportParameters';
import { AzureReachabilityReport } from '../models/AzureReachabilityReport';
import { AvailableProvidersListParameters } from '../models/AvailableProvidersListParameters';
import { AvailableProvidersList } from '../models/AvailableProvidersList';
import { NetworkConfigurationDiagnosticParameters } from '../models/NetworkConfigurationDiagnosticParameters';
import { NetworkConfigurationDiagnosticResponse } from '../models/NetworkConfigurationDiagnosticResponse';
import { ConnectionMonitorResult } from '../models/ConnectionMonitorResult';
import { ConnectionMonitor } from '../models/ConnectionMonitor';
import { ConnectionMonitorQueryResult } from '../models/ConnectionMonitorQueryResult';
import { ConnectionMonitorListResult } from '../models/ConnectionMonitorListResult';
import { FlowLog } from '../models/FlowLog';
import { FlowLogListResult } from '../models/FlowLogListResult';
import { OperationListResult } from '../models/OperationListResult';
import { PrivateEndpoint } from '../models/PrivateEndpoint';
import { PrivateEndpointListResult } from '../models/PrivateEndpointListResult';
import { AvailablePrivateEndpointTypesResult } from '../models/AvailablePrivateEndpointTypesResult';
import { PrivateLinkService } from '../models/PrivateLinkService';
import { PrivateLinkServiceListResult } from '../models/PrivateLinkServiceListResult';
import { PrivateEndpointConnection } from '../models/PrivateEndpointConnection';
import { PrivateEndpointConnectionListResult } from '../models/PrivateEndpointConnectionListResult';
import { CheckPrivateLinkServiceVisibilityRequest } from '../models/CheckPrivateLinkServiceVisibilityRequest';
import { PrivateLinkServiceVisibility } from '../models/PrivateLinkServiceVisibility';
import { AutoApprovedPrivateLinkServicesResult } from '../models/AutoApprovedPrivateLinkServicesResult';
import { PublicIPAddress } from '../models/PublicIPAddress';
import { PublicIPAddressListResult } from '../models/PublicIPAddressListResult';
import { PublicIPPrefix } from '../models/PublicIPPrefix';
import { PublicIPPrefixListResult } from '../models/PublicIPPrefixListResult';
import { RouteFilter } from '../models/RouteFilter';
import { RouteFilterListResult } from '../models/RouteFilterListResult';
import { RouteFilterRule } from '../models/RouteFilterRule';
import { RouteFilterRuleListResult } from '../models/RouteFilterRuleListResult';
import { RouteTable } from '../models/RouteTable';
import { RouteTableListResult } from '../models/RouteTableListResult';
import { Route } from '../models/Route';
import { RouteListResult } from '../models/RouteListResult';
import { BgpServiceCommunityListResult } from '../models/BgpServiceCommunityListResult';
import { ServiceEndpointPolicy } from '../models/ServiceEndpointPolicy';
import { ServiceEndpointPolicyListResult } from '../models/ServiceEndpointPolicyListResult';
import { ServiceEndpointPolicyDefinition } from '../models/ServiceEndpointPolicyDefinition';
import { ServiceEndpointPolicyDefinitionListResult } from '../models/ServiceEndpointPolicyDefinitionListResult';
import { ServiceTagsListResult } from '../models/ServiceTagsListResult';
import { UsagesListResult } from '../models/UsagesListResult';
import { VirtualNetwork } from '../models/VirtualNetwork';
import { VirtualNetworkListResult } from '../models/VirtualNetworkListResult';
import { Subnet } from '../models/Subnet';
import { PrepareNetworkPoliciesRequest } from '../models/PrepareNetworkPoliciesRequest';
import { UnprepareNetworkPoliciesRequest } from '../models/UnprepareNetworkPoliciesRequest';
import { ResourceNavigationLinksListResult } from '../models/ResourceNavigationLinksListResult';
import { ServiceAssociationLinksListResult } from '../models/ServiceAssociationLinksListResult';
import { SubnetListResult } from '../models/SubnetListResult';
import { VirtualNetworkPeering } from '../models/VirtualNetworkPeering';
import { VirtualNetworkPeeringListResult } from '../models/VirtualNetworkPeeringListResult';
import { IPAddressAvailabilityResult } from '../models/IPAddressAvailabilityResult';
import { VirtualNetworkListUsageResult } from '../models/VirtualNetworkListUsageResult';
import { VirtualNetworkGateway } from '../models/VirtualNetworkGateway';
import { VirtualNetworkGatewayListResult } from '../models/VirtualNetworkGatewayListResult';
import { VirtualNetworkGatewayListConnectionsResult } from '../models/VirtualNetworkGatewayListConnectionsResult';
import { VpnClientParameters } from '../models/VpnClientParameters';
import { BgpPeerStatusListResult } from '../models/BgpPeerStatusListResult';
import { GatewayRouteListResult } from '../models/GatewayRouteListResult';
import { VpnClientIPsecParameters } from '../models/VpnClientIPsecParameters';
import { VpnDeviceScriptParameters } from '../models/VpnDeviceScriptParameters';
import { VpnPacketCaptureStartParameters } from '../models/VpnPacketCaptureStartParameters';
import { VpnPacketCaptureStopParameters } from '../models/VpnPacketCaptureStopParameters';
import { VirtualNetworkGatewayConnection } from '../models/VirtualNetworkGatewayConnection';
import { ConnectionSharedKey } from '../models/ConnectionSharedKey';
import { VirtualNetworkGatewayConnectionListResult } from '../models/VirtualNetworkGatewayConnectionListResult';
import { ConnectionResetSharedKey } from '../models/ConnectionResetSharedKey';
import { LocalNetworkGateway } from '../models/LocalNetworkGateway';
import { LocalNetworkGatewayListResult } from '../models/LocalNetworkGatewayListResult';
import { VpnClientConnectionHealthDetailListResult } from '../models/VpnClientConnectionHealthDetailListResult';
import { P2SVpnConnectionRequest } from '../models/P2SVpnConnectionRequest';
import { VirtualNetworkTap } from '../models/VirtualNetworkTap';
import { VirtualNetworkTapListResult } from '../models/VirtualNetworkTapListResult';
import { VirtualRouter } from '../models/VirtualRouter';
import { VirtualRouterListResult } from '../models/VirtualRouterListResult';
import { VirtualRouterPeering } from '../models/VirtualRouterPeering';
import { VirtualRouterPeeringListResult } from '../models/VirtualRouterPeeringListResult';
import { VirtualWAN } from '../models/VirtualWAN';
import { ListVirtualWANsResult } from '../models/ListVirtualWANsResult';
import { VpnSite } from '../models/VpnSite';
import { ListVpnSitesResult } from '../models/ListVpnSitesResult';
import { VpnSiteLink } from '../models/VpnSiteLink';
import { ListVpnSiteLinksResult } from '../models/ListVpnSiteLinksResult';
import { GetVpnSitesConfigurationRequest } from '../models/GetVpnSitesConfigurationRequest';
import { VirtualWanSecurityProviders } from '../models/VirtualWanSecurityProviders';
import { VpnServerConfiguration } from '../models/VpnServerConfiguration';
import { ListVpnServerConfigurationsResult } from '../models/ListVpnServerConfigurationsResult';
import { VirtualHub } from '../models/VirtualHub';
import { ListVirtualHubsResult } from '../models/ListVirtualHubsResult';
import { HubVirtualNetworkConnection } from '../models/HubVirtualNetworkConnection';
import { ListHubVirtualNetworkConnectionsResult } from '../models/ListHubVirtualNetworkConnectionsResult';
import { VpnGateway } from '../models/VpnGateway';
import { ListVpnGatewaysResult } from '../models/ListVpnGatewaysResult';
import { VpnConnection } from '../models/VpnConnection';
import { VpnSiteLinkConnection } from '../models/VpnSiteLinkConnection';
import { ListVpnConnectionsResult } from '../models/ListVpnConnectionsResult';
import { ListVpnSiteLinkConnectionsResult } from '../models/ListVpnSiteLinkConnectionsResult';
import { P2SVpnGateway } from '../models/P2SVpnGateway';
import { ListP2SVpnGatewaysResult } from '../models/ListP2SVpnGatewaysResult';
import { P2SVpnProfileParameters } from '../models/P2SVpnProfileParameters';
import { VpnProfileResponse } from '../models/VpnProfileResponse';
import { P2SVpnConnectionHealthRequest } from '../models/P2SVpnConnectionHealthRequest';
import { P2SVpnConnectionHealth } from '../models/P2SVpnConnectionHealth';
import { VpnServerConfigurationsResponse } from '../models/VpnServerConfigurationsResponse';
import { VirtualWanVpnProfileParameters } from '../models/VirtualWanVpnProfileParameters';
import { VirtualHubRouteTableV2 } from '../models/VirtualHubRouteTableV2';
import { ListVirtualHubRouteTableV2sResult } from '../models/ListVirtualHubRouteTableV2sResult';
import { WebApplicationFirewallPolicyListResult } from '../models/WebApplicationFirewallPolicyListResult';
import { WebApplicationFirewallPolicy } from '../models/WebApplicationFirewallPolicy';
export type schema = ApplicationGateway;
export type schema = CloudError;
export type schema = ApplicationGateway;
export type schema = ApplicationGateway;
export type schema = ApplicationGateway;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = ApplicationGateway;
export type schema = CloudError;
export type schema = ApplicationGatewayListResult;
export type schema = CloudError;
export type schema = ApplicationGatewayListResult;
export type schema = CloudError;
export type schema = CloudError;
export type schema = CloudError;
export type schema = ApplicationGatewayBackendHealth;
export type schema = CloudError;
export type schema = ApplicationGatewayOnDemandProbe;
export type schema = ApplicationGatewayBackendHealthOnDemand;
export type schema = CloudError;
export type schema = Array<string>;
export type schema = Error;
export type schema = Array<string>;
export type schema = Error;
export type schema = Array<string>;
export type schema = Error;
export type schema = ApplicationGatewayAvailableWafRuleSetsResult;
export type schema = CloudError;
export type schema = ApplicationGatewayAvailableSslOptions;
export type schema = CloudError;
export type schema = ApplicationGatewayAvailableSslPredefinedPolicies;
export type schema = CloudError;
export type schema = ApplicationGatewaySslPredefinedPolicy;
export type schema = CloudError;
export type schema = ApplicationSecurityGroup;
export type schema = CloudError;
export type schema = ApplicationSecurityGroup;
export type schema = ApplicationSecurityGroup;
export type schema = ApplicationSecurityGroup;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = ApplicationSecurityGroup;
export type schema = CloudError;
export type schema = ApplicationSecurityGroupListResult;
export type schema = CloudError;
export type schema = ApplicationSecurityGroupListResult;
export type schema = CloudError;
export type schema = AvailableDelegationsResult;
export type schema = CloudError;
export type schema = AvailableDelegationsResult;
export type schema = CloudError;
export type schema = AvailableServiceAliasesResult;
export type schema = CloudError;
export type schema = AvailableServiceAliasesResult;
export type schema = CloudError;
export type schema = AzureFirewall;
export type schema = CloudError;
export type schema = AzureFirewall;
export type schema = AzureFirewall;
export type schema = AzureFirewall;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = AzureFirewall;
export type schema = CloudError;
export type schema = AzureFirewallListResult;
export type schema = CloudError;
export type schema = AzureFirewallListResult;
export type schema = CloudError;
export type schema = AzureFirewallFqdnTagListResult;
export type schema = CloudError;
export type schema = BastionShareableLinkListRequest;
export type schema = SessionIds;
export type schema = BastionHost;
export type schema = CloudError;
export type schema = BastionHost;
export type schema = BastionHost;
export type schema = BastionHost;
export type schema = CloudError;
export type schema = CloudError;
export type schema = BastionHostListResult;
export type schema = CloudError;
export type schema = BastionHostListResult;
export type schema = CloudError;
export type schema = BastionShareableLinkListResult;
export type schema = CloudError;
export type schema = CloudError;
export type schema = BastionShareableLinkListResult;
export type schema = CloudError;
export type schema = BastionActiveSessionListResult;
export type schema = CloudError;
export type schema = BastionSessionDeleteResult;
export type schema = CloudError;
export type schema = DnsNameAvailabilityResult;
export type schema = CloudError;
export type schema = DdosCustomPolicy;
export type schema = CloudError;
export type schema = DdosCustomPolicy;
export type schema = DdosCustomPolicy;
export type schema = DdosCustomPolicy;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = DdosCustomPolicy;
export type schema = CloudError;
export type schema = DdosProtectionPlan;
export type schema = CloudError;
export type schema = DdosProtectionPlan;
export type schema = DdosProtectionPlan;
export type schema = DdosProtectionPlan;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = DdosProtectionPlan;
export type schema = CloudError;
export type schema = DdosProtectionPlanListResult;
export type schema = CloudError;
export type schema = DdosProtectionPlanListResult;
export type schema = CloudError;
export type schema = EndpointServicesListResult;
export type schema = CloudError;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = CloudError;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = CloudError;
export type schema = CloudError;
export type schema = AuthorizationListResult;
export type schema = CloudError;
export type schema = ExpressRouteCircuitPeering;
export type schema = CloudError;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = CloudError;
export type schema = CloudError;
export type schema = ExpressRouteCircuitPeeringListResult;
export type schema = CloudError;
export type schema = ExpressRouteCircuitConnection;
export type schema = CloudError;
export type schema = ExpressRouteCircuitConnection;
export type schema = ExpressRouteCircuitConnection;
export type schema = ExpressRouteCircuitConnection;
export type schema = CloudError;
export type schema = CloudError;
export type schema = ExpressRouteCircuitConnectionListResult;
export type schema = CloudError;
export type schema = PeerExpressRouteCircuitConnection;
export type schema = CloudError;
export type schema = PeerExpressRouteCircuitConnectionListResult;
export type schema = CloudError;
export type schema = ExpressRouteCircuit;
export type schema = CloudError;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = ExpressRouteCircuit;
export type schema = CloudError;
export type schema = ExpressRouteCircuitsArpTableListResult;
export type schema = CloudError;
export type schema = ExpressRouteCircuitsRoutesTableListResult;
export type schema = CloudError;
export type schema = ExpressRouteCircuitsRoutesTableSummaryListResult;
export type schema = CloudError;
export type schema = ExpressRouteCircuitStats;
export type schema = CloudError;
export type schema = ExpressRouteCircuitStats;
export type schema = CloudError;
export type schema = ExpressRouteCircuitListResult;
export type schema = CloudError;
export type schema = ExpressRouteCircuitListResult;
export type schema = CloudError;
export type schema = ExpressRouteServiceProviderListResult;
export type schema = CloudError;
export type schema = ExpressRouteCrossConnectionListResult;
export type schema = CloudError;
export type schema = ExpressRouteCrossConnectionListResult;
export type schema = CloudError;
export type schema = ExpressRouteCrossConnection;
export type schema = CloudError;
export type schema = ExpressRouteCrossConnection;
export type schema = ExpressRouteCrossConnection;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = ExpressRouteCrossConnection;
export type schema = CloudError;
export type schema = ExpressRouteCrossConnectionPeeringList;
export type schema = CloudError;
export type schema = ExpressRouteCrossConnectionPeering;
export type schema = CloudError;
export type schema = ExpressRouteCrossConnectionPeering;
export type schema = ExpressRouteCrossConnectionPeering;
export type schema = ExpressRouteCrossConnectionPeering;
export type schema = CloudError;
export type schema = CloudError;
export type schema = ExpressRouteCircuitsArpTableListResult;
export type schema = CloudError;
export type schema = ExpressRouteCrossConnectionsRoutesTableSummaryListResult;
export type schema = CloudError;
export type schema = ExpressRouteCircuitsRoutesTableListResult;
export type schema = CloudError;
export type schema = ExpressRouteGatewayList;
export type schema = CloudError;
export type schema = ExpressRouteGatewayList;
export type schema = CloudError;
export type schema = ExpressRouteGateway;
export type schema = CloudError;
export type schema = ExpressRouteGateway;
export type schema = ExpressRouteGateway;
export type schema = ExpressRouteGateway;
export type schema = CloudError;
export type schema = CloudError;
export type schema = ExpressRouteConnection;
export type schema = CloudError;
export type schema = ExpressRouteConnection;
export type schema = ExpressRouteConnection;
export type schema = ExpressRouteConnection;
export type schema = CloudError;
export type schema = CloudError;
export type schema = ExpressRouteConnectionList;
export type schema = CloudError;
export type schema = ExpressRoutePortsLocationListResult;
export type schema = CloudError;
export type schema = ExpressRoutePortsLocation;
export type schema = CloudError;
export type schema = ExpressRoutePort;
export type schema = CloudError;
export type schema = ExpressRoutePort;
export type schema = ExpressRoutePort;
export type schema = ExpressRoutePort;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = ExpressRoutePort;
export type schema = CloudError;
export type schema = ExpressRoutePortListResult;
export type schema = CloudError;
export type schema = ExpressRoutePortListResult;
export type schema = CloudError;
export type schema = ExpressRouteLink;
export type schema = CloudError;
export type schema = ExpressRouteLinkListResult;
export type schema = CloudError;
export type schema = FirewallPolicy;
export type schema = CloudError;
export type schema = FirewallPolicy;
export type schema = FirewallPolicy;
export type schema = FirewallPolicy;
export type schema = CloudError;
export type schema = CloudError;
export type schema = FirewallPolicyListResult;
export type schema = CloudError;
export type schema = FirewallPolicyListResult;
export type schema = CloudError;
export type schema = FirewallPolicyRuleGroup;
export type schema = CloudError;
export type schema = FirewallPolicyRuleGroup;
export type schema = FirewallPolicyRuleGroup;
export type schema = FirewallPolicyRuleGroup;
export type schema = CloudError;
export type schema = CloudError;
export type schema = FirewallPolicyRuleGroupListResult;
export type schema = CloudError;
export type schema = IpGroup;
export type schema = Error;
export type schema = IpGroup;
export type schema = IpGroup;
export type schema = IpGroup;
export type schema = Error;
export type schema = Error;
export type schema = TagsObject;
export type schema = IpGroup;
export type schema = Error;
export type schema = IpGroupListResult;
export type schema = Error;
export type schema = IpGroupListResult;
export type schema = Error;
export type schema = LoadBalancer;
export type schema = CloudError;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = LoadBalancer;
export type schema = CloudError;
export type schema = LoadBalancerListResult;
export type schema = CloudError;
export type schema = LoadBalancerListResult;
export type schema = CloudError;
export type schema = LoadBalancerBackendAddressPoolListResult;
export type schema = CloudError;
export type schema = BackendAddressPool;
export type schema = CloudError;
export type schema = LoadBalancerFrontendIPConfigurationListResult;
export type schema = CloudError;
export type schema = FrontendIPConfiguration;
export type schema = CloudError;
export type schema = InboundNatRuleListResult;
export type schema = CloudError;
export type schema = InboundNatRule;
export type schema = CloudError;
export type schema = InboundNatRule;
export type schema = InboundNatRule;
export type schema = InboundNatRule;
export type schema = CloudError;
export type schema = CloudError;
export type schema = LoadBalancerLoadBalancingRuleListResult;
export type schema = CloudError;
export type schema = LoadBalancingRule;
export type schema = CloudError;
export type schema = LoadBalancerOutboundRuleListResult;
export type schema = CloudError;
export type schema = OutboundRule;
export type schema = CloudError;
export type schema = NetworkInterfaceListResult;
export type schema = CloudError;
export type schema = LoadBalancerProbeListResult;
export type schema = CloudError;
export type schema = Probe;
export type schema = CloudError;
export type schema = NatGateway;
export type schema = CloudError;
export type schema = NatGateway;
export type schema = NatGateway;
export type schema = NatGateway;
export type schema = NatGateway;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = NatGateway;
export type schema = CloudError;
export type schema = NatGatewayListResult;
export type schema = CloudError;
export type schema = NatGatewayListResult;
export type schema = CloudError;
export type schema = NetworkInterface;
export type schema = CloudError;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = NetworkInterface;
export type schema = CloudError;
export type schema = NetworkInterfaceListResult;
export type schema = CloudError;
export type schema = NetworkInterfaceListResult;
export type schema = CloudError;
export type schema = EffectiveRouteListResult;
export type schema = CloudError;
export type schema = EffectiveNetworkSecurityGroupListResult;
export type schema = CloudError;
export type schema = NetworkInterfaceIPConfigurationListResult;
export type schema = CloudError;
export type schema = NetworkInterfaceIPConfiguration;
export type schema = CloudError;
export type schema = NetworkInterfaceLoadBalancerListResult;
export type schema = CloudError;
export type schema = NetworkInterfaceTapConfiguration;
export type schema = CloudError;
export type schema = NetworkInterfaceTapConfiguration;
export type schema = NetworkInterfaceTapConfiguration;
export type schema = NetworkInterfaceTapConfiguration;
export type schema = CloudError;
export type schema = CloudError;
export type schema = NetworkInterfaceTapConfigurationListResult;
export type schema = CloudError;
export type schema = NetworkProfile;
export type schema = CloudError;
export type schema = NetworkProfile;
export type schema = NetworkProfile;
export type schema = NetworkProfile;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = NetworkProfile;
export type schema = CloudError;
export type schema = NetworkProfileListResult;
export type schema = CloudError;
export type schema = NetworkProfileListResult;
export type schema = CloudError;
export type schema = NetworkSecurityGroup;
export type schema = CloudError;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = NetworkSecurityGroup;
export type schema = CloudError;
export type schema = NetworkSecurityGroupListResult;
export type schema = CloudError;
export type schema = NetworkSecurityGroupListResult;
export type schema = CloudError;
export type schema = SecurityRule;
export type schema = CloudError;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = CloudError;
export type schema = CloudError;
export type schema = SecurityRuleListResult;
export type schema = CloudError;
export type schema = SecurityRuleListResult;
export type schema = CloudError;
export type schema = SecurityRule;
export type schema = CloudError;
export type schema = NetworkVirtualAppliance;
export type schema = CloudError;
export type schema = NetworkVirtualAppliance;
export type schema = NetworkVirtualAppliance;
export type schema = NetworkVirtualAppliance;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = NetworkVirtualAppliance;
export type schema = CloudError;
export type schema = NetworkVirtualApplianceListResult;
export type schema = CloudError;
export type schema = NetworkVirtualApplianceListResult;
export type schema = CloudError;
export type schema = NetworkWatcher;
export type schema = ErrorResponse;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = ErrorResponse;
export type schema = ErrorResponse;
export type schema = TagsObject;
export type schema = NetworkWatcher;
export type schema = ErrorResponse;
export type schema = NetworkWatcherListResult;
export type schema = ErrorResponse;
export type schema = NetworkWatcherListResult;
export type schema = ErrorResponse;
export type schema = TopologyParameters;
export type schema = Topology;
export type schema = ErrorResponse;
export type schema = VerificationIPFlowParameters;
export type schema = VerificationIPFlowResult;
export type schema = VerificationIPFlowResult;
export type schema = ErrorResponse;
export type schema = NextHopParameters;
export type schema = NextHopResult;
export type schema = NextHopResult;
export type schema = ErrorResponse;
export type schema = SecurityGroupViewParameters;
export type schema = SecurityGroupViewResult;
export type schema = SecurityGroupViewResult;
export type schema = ErrorResponse;
export type schema = PacketCaptureResult;
export type schema = ErrorResponse;
export type schema = PacketCapture;
export type schema = PacketCaptureResult;
export type schema = ErrorResponse;
export type schema = ErrorResponse;
export type schema = ErrorResponse;
export type schema = PacketCaptureQueryStatusResult;
export type schema = PacketCaptureQueryStatusResult;
export type schema = ErrorResponse;
export type schema = PacketCaptureListResult;
export type schema = ErrorResponse;
export type schema = TroubleshootingParameters;
export type schema = TroubleshootingResult;
export type schema = TroubleshootingResult;
export type schema = ErrorResponse;
export type schema = QueryTroubleshootingParameters;
export type schema = TroubleshootingResult;
export type schema = TroubleshootingResult;
export type schema = ErrorResponse;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = ErrorResponse;
export type schema = FlowLogStatusParameters;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = ErrorResponse;
export type schema = ConnectivityParameters;
export type schema = ConnectivityInformation;
export type schema = ConnectivityInformation;
export type schema = ErrorResponse;
export type schema = AzureReachabilityReportParameters;
export type schema = AzureReachabilityReport;
export type schema = AzureReachabilityReport;
export type schema = ErrorResponse;
export type schema = AvailableProvidersListParameters;
export type schema = AvailableProvidersList;
export type schema = AvailableProvidersList;
export type schema = ErrorResponse;
export type schema = NetworkConfigurationDiagnosticParameters;
export type schema = NetworkConfigurationDiagnosticResponse;
export type schema = NetworkConfigurationDiagnosticResponse;
export type schema = ErrorResponse;
export type schema = ConnectionMonitorResult;
export type schema = ErrorResponse;
export type schema = ConnectionMonitor;
export type schema = ConnectionMonitorResult;
export type schema = ConnectionMonitorResult;
export type schema = ErrorResponse;
export type schema = ErrorResponse;
export type schema = TagsObject;
export type schema = ConnectionMonitorResult;
export type schema = ErrorResponse;
export type schema = ErrorResponse;
export type schema = ErrorResponse;
export type schema = ConnectionMonitorQueryResult;
export type schema = ConnectionMonitorQueryResult;
export type schema = ErrorResponse;
export type schema = ConnectionMonitorListResult;
export type schema = ErrorResponse;
export type schema = FlowLog;
export type schema = ErrorResponse;
export type schema = FlowLog;
export type schema = FlowLog;
export type schema = FlowLog;
export type schema = ErrorResponse;
export type schema = ErrorResponse;
export type schema = FlowLogListResult;
export type schema = ErrorResponse;
export type schema = OperationListResult;
export type schema = CloudError;
export type schema = PrivateEndpoint;
export type schema = Error;
export type schema = PrivateEndpoint;
export type schema = PrivateEndpoint;
export type schema = PrivateEndpoint;
export type schema = Error;
export type schema = Error;
export type schema = PrivateEndpointListResult;
export type schema = Error;
export type schema = PrivateEndpointListResult;
export type schema = Error;
export type schema = AvailablePrivateEndpointTypesResult;
export type schema = CloudError;
export type schema = AvailablePrivateEndpointTypesResult;
export type schema = CloudError;
export type schema = PrivateLinkService;
export type schema = Error;
export type schema = PrivateLinkService;
export type schema = PrivateLinkService;
export type schema = PrivateLinkService;
export type schema = Error;
export type schema = Error;
export type schema = PrivateLinkServiceListResult;
export type schema = Error;
export type schema = PrivateLinkServiceListResult;
export type schema = Error;
export type schema = PrivateEndpointConnection;
export type schema = Error;
export type schema = PrivateEndpointConnection;
export type schema = PrivateEndpointConnection;
export type schema = Error;
export type schema = Error;
export type schema = PrivateEndpointConnectionListResult;
export type schema = Error;
export type schema = CheckPrivateLinkServiceVisibilityRequest;
export type schema = PrivateLinkServiceVisibility;
export type schema = CloudError;
export type schema = CheckPrivateLinkServiceVisibilityRequest;
export type schema = PrivateLinkServiceVisibility;
export type schema = CloudError;
export type schema = AutoApprovedPrivateLinkServicesResult;
export type schema = CloudError;
export type schema = AutoApprovedPrivateLinkServicesResult;
export type schema = CloudError;
export type schema = PublicIPAddress;
export type schema = CloudError;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = PublicIPAddress;
export type schema = CloudError;
export type schema = PublicIPAddressListResult;
export type schema = CloudError;
export type schema = PublicIPAddressListResult;
export type schema = CloudError;
export type schema = PublicIPPrefix;
export type schema = CloudError;
export type schema = PublicIPPrefix;
export type schema = PublicIPPrefix;
export type schema = PublicIPPrefix;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = PublicIPPrefix;
export type schema = CloudError;
export type schema = PublicIPPrefixListResult;
export type schema = CloudError;
export type schema = PublicIPPrefixListResult;
export type schema = CloudError;
export type schema = RouteFilter;
export type schema = CloudError;
export type schema = RouteFilter;
export type schema = RouteFilter;
export type schema = RouteFilter;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = RouteFilter;
export type schema = CloudError;
export type schema = RouteFilterListResult;
export type schema = CloudError;
export type schema = RouteFilterListResult;
export type schema = CloudError;
export type schema = RouteFilterRule;
export type schema = CloudError;
export type schema = RouteFilterRule;
export type schema = RouteFilterRule;
export type schema = RouteFilterRule;
export type schema = CloudError;
export type schema = CloudError;
export type schema = RouteFilterRuleListResult;
export type schema = CloudError;
export type schema = RouteTable;
export type schema = CloudError;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = RouteTable;
export type schema = CloudError;
export type schema = RouteTableListResult;
export type schema = CloudError;
export type schema = RouteTableListResult;
export type schema = CloudError;
export type schema = Route;
export type schema = CloudError;
export type schema = Route;
export type schema = Route;
export type schema = Route;
export type schema = CloudError;
export type schema = CloudError;
export type schema = RouteListResult;
export type schema = CloudError;
export type schema = BgpServiceCommunityListResult;
export type schema = CloudError;
export type schema = ServiceEndpointPolicy;
export type schema = CloudError;
export type schema = ServiceEndpointPolicy;
export type schema = ServiceEndpointPolicy;
export type schema = ServiceEndpointPolicy;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = ServiceEndpointPolicy;
export type schema = CloudError;
export type schema = ServiceEndpointPolicyListResult;
export type schema = CloudError;
export type schema = ServiceEndpointPolicyListResult;
export type schema = CloudError;
export type schema = ServiceEndpointPolicyDefinition;
export type schema = CloudError;
export type schema = ServiceEndpointPolicyDefinition;
export type schema = ServiceEndpointPolicyDefinition;
export type schema = ServiceEndpointPolicyDefinition;
export type schema = CloudError;
export type schema = CloudError;
export type schema = ServiceEndpointPolicyDefinitionListResult;
export type schema = CloudError;
export type schema = ServiceTagsListResult;
export type schema = CloudError;
export type schema = UsagesListResult;
export type schema = CloudError;
export type schema = VirtualNetwork;
export type schema = CloudError;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = VirtualNetwork;
export type schema = CloudError;
export type schema = VirtualNetworkListResult;
export type schema = CloudError;
export type schema = VirtualNetworkListResult;
export type schema = CloudError;
export type schema = Subnet;
export type schema = CloudError;
export type schema = Subnet;
export type schema = Subnet;
export type schema = Subnet;
export type schema = CloudError;
export type schema = CloudError;
export type schema = PrepareNetworkPoliciesRequest;
export type schema = CloudError;
export type schema = UnprepareNetworkPoliciesRequest;
export type schema = CloudError;
export type schema = ResourceNavigationLinksListResult;
export type schema = CloudError;
export type schema = ServiceAssociationLinksListResult;
export type schema = CloudError;
export type schema = SubnetListResult;
export type schema = CloudError;
export type schema = VirtualNetworkPeering;
export type schema = CloudError;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = CloudError;
export type schema = CloudError;
export type schema = VirtualNetworkPeeringListResult;
export type schema = CloudError;
export type schema = IPAddressAvailabilityResult;
export type schema = CloudError;
export type schema = VirtualNetworkListUsageResult;
export type schema = CloudError;
export type schema = VirtualNetworkGateway;
export type schema = CloudError;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = VirtualNetworkGateway;
export type schema = CloudError;
export type schema = VirtualNetworkGatewayListResult;
export type schema = CloudError;
export type schema = VirtualNetworkGatewayListConnectionsResult;
export type schema = CloudError;
export type schema = VirtualNetworkGateway;
export type schema = CloudError;
export type schema = CloudError;
export type schema = VpnClientParameters;
export type schema = CloudError;
export type schema = VpnClientParameters;
export type schema = CloudError;
export type schema = CloudError;
export type schema = BgpPeerStatusListResult;
export type schema = CloudError;
export type schema = CloudError;
export type schema = GatewayRouteListResult;
export type schema = CloudError;
export type schema = GatewayRouteListResult;
export type schema = CloudError;
export type schema = VpnClientIPsecParameters;
export type schema = VpnClientIPsecParameters;
export type schema = CloudError;
export type schema = VpnClientIPsecParameters;
export type schema = CloudError;
export type schema = VpnDeviceScriptParameters;
export type schema = CloudError;
export type schema = VpnPacketCaptureStartParameters;
export type schema = Error;
export type schema = VpnPacketCaptureStopParameters;
export type schema = Error;
export type schema = VirtualNetworkGatewayConnection;
export type schema = CloudError;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = VirtualNetworkGatewayConnection;
export type schema = CloudError;
export type schema = ConnectionSharedKey;
export type schema = CloudError;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = CloudError;
export type schema = VirtualNetworkGatewayConnectionListResult;
export type schema = CloudError;
export type schema = ConnectionResetSharedKey;
export type schema = ConnectionResetSharedKey;
export type schema = CloudError;
export type schema = VpnPacketCaptureStartParameters;
export type schema = Error;
export type schema = VpnPacketCaptureStopParameters;
export type schema = Error;
export type schema = LocalNetworkGateway;
export type schema = CloudError;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = LocalNetworkGateway;
export type schema = CloudError;
export type schema = LocalNetworkGatewayListResult;
export type schema = CloudError;
export type schema = VpnClientConnectionHealthDetailListResult;
export type schema = CloudError;
export type schema = P2SVpnConnectionRequest;
export type schema = CloudError;
export type schema = VirtualNetworkTap;
export type schema = CloudError;
export type schema = VirtualNetworkTap;
export type schema = VirtualNetworkTap;
export type schema = VirtualNetworkTap;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = VirtualNetworkTap;
export type schema = CloudError;
export type schema = VirtualNetworkTapListResult;
export type schema = CloudError;
export type schema = VirtualNetworkTapListResult;
export type schema = CloudError;
export type schema = VirtualRouter;
export type schema = Error;
export type schema = VirtualRouter;
export type schema = VirtualRouter;
export type schema = VirtualRouter;
export type schema = Error;
export type schema = Error;
export type schema = VirtualRouterListResult;
export type schema = Error;
export type schema = VirtualRouterListResult;
export type schema = Error;
export type schema = VirtualRouterPeering;
export type schema = Error;
export type schema = VirtualRouterPeering;
export type schema = VirtualRouterPeering;
export type schema = VirtualRouterPeering;
export type schema = Error;
export type schema = Error;
export type schema = VirtualRouterPeeringListResult;
export type schema = Error;
export type schema = VirtualWAN;
export type schema = CloudError;
export type schema = VirtualWAN;
export type schema = VirtualWAN;
export type schema = VirtualWAN;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = VirtualWAN;
export type schema = CloudError;
export type schema = ListVirtualWANsResult;
export type schema = CloudError;
export type schema = ListVirtualWANsResult;
export type schema = CloudError;
export type schema = VpnSite;
export type schema = CloudError;
export type schema = VpnSite;
export type schema = VpnSite;
export type schema = VpnSite;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = VpnSite;
export type schema = CloudError;
export type schema = ListVpnSitesResult;
export type schema = CloudError;
export type schema = VpnSiteLink;
export type schema = CloudError;
export type schema = ListVpnSiteLinksResult;
export type schema = CloudError;
export type schema = ListVpnSitesResult;
export type schema = CloudError;
export type schema = GetVpnSitesConfigurationRequest;
export type schema = CloudError;
export type schema = VirtualWanSecurityProviders;
export type schema = CloudError;
export type schema = VpnServerConfiguration;
export type schema = CloudError;
export type schema = VpnServerConfiguration;
export type schema = VpnServerConfiguration;
export type schema = VpnServerConfiguration;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = VpnServerConfiguration;
export type schema = CloudError;
export type schema = ListVpnServerConfigurationsResult;
export type schema = CloudError;
export type schema = ListVpnServerConfigurationsResult;
export type schema = CloudError;
export type schema = VirtualHub;
export type schema = CloudError;
export type schema = VirtualHub;
export type schema = VirtualHub;
export type schema = VirtualHub;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = VirtualHub;
export type schema = CloudError;
export type schema = ListVirtualHubsResult;
export type schema = CloudError;
export type schema = ListVirtualHubsResult;
export type schema = CloudError;
export type schema = HubVirtualNetworkConnection;
export type schema = CloudError;
export type schema = ListHubVirtualNetworkConnectionsResult;
export type schema = CloudError;
export type schema = VpnGateway;
export type schema = CloudError;
export type schema = VpnGateway;
export type schema = VpnGateway;
export type schema = VpnGateway;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = VpnGateway;
export type schema = CloudError;
export type schema = VpnGateway;
export type schema = CloudError;
export type schema = ListVpnGatewaysResult;
export type schema = CloudError;
export type schema = ListVpnGatewaysResult;
export type schema = CloudError;
export type schema = VpnConnection;
export type schema = CloudError;
export type schema = VpnConnection;
export type schema = VpnConnection;
export type schema = VpnConnection;
export type schema = CloudError;
export type schema = CloudError;
export type schema = VpnSiteLinkConnection;
export type schema = CloudError;
export type schema = ListVpnConnectionsResult;
export type schema = CloudError;
export type schema = ListVpnSiteLinkConnectionsResult;
export type schema = CloudError;
export type schema = P2SVpnGateway;
export type schema = CloudError;
export type schema = P2SVpnGateway;
export type schema = P2SVpnGateway;
export type schema = P2SVpnGateway;
export type schema = CloudError;
export type schema = CloudError;
export type schema = TagsObject;
export type schema = P2SVpnGateway;
export type schema = CloudError;
export type schema = ListP2SVpnGatewaysResult;
export type schema = CloudError;
export type schema = ListP2SVpnGatewaysResult;
export type schema = CloudError;
export type schema = P2SVpnProfileParameters;
export type schema = VpnProfileResponse;
export type schema = CloudError;
export type schema = P2SVpnGateway;
export type schema = CloudError;
export type schema = P2SVpnConnectionHealthRequest;
export type schema = P2SVpnConnectionHealth;
export type schema = CloudError;
export type schema = VpnServerConfigurationsResponse;
export type schema = CloudError;
export type schema = VirtualWanVpnProfileParameters;
export type schema = VpnProfileResponse;
export type schema = CloudError;
export type schema = VirtualHubRouteTableV2;
export type schema = Error;
export type schema = VirtualHubRouteTableV2;
export type schema = VirtualHubRouteTableV2;
export type schema = VirtualHubRouteTableV2;
export type schema = Error;
export type schema = Error;
export type schema = ListVirtualHubRouteTableV2sResult;
export type schema = CloudError;
export type schema = P2SVpnConnectionRequest;
export type schema = CloudError;
export type schema = NetworkInterfaceListResult;
export type schema = CloudError;
export type schema = NetworkInterfaceListResult;
export type schema = CloudError;
export type schema = NetworkInterface;
export type schema = CloudError;
export type schema = NetworkInterfaceIPConfigurationListResult;
export type schema = CloudError;
export type schema = NetworkInterfaceIPConfiguration;
export type schema = CloudError;
export type schema = PublicIPAddressListResult;
export type schema = CloudError;
export type schema = PublicIPAddressListResult;
export type schema = CloudError;
export type schema = PublicIPAddress;
export type schema = CloudError;
export type schema = WebApplicationFirewallPolicyListResult;
export type schema = CloudError;
export type schema = WebApplicationFirewallPolicyListResult;
export type schema = CloudError;
export type schema = WebApplicationFirewallPolicy;
export type schema = CloudError;
export type schema = WebApplicationFirewallPolicy;
export type schema = WebApplicationFirewallPolicy;
export type schema = WebApplicationFirewallPolicy;
export type schema = CloudError;
export type schema = CloudError;
