import { NetworkInterfaceListResult } from '../models/NetworkInterfaceListResult';
import { NetworkInterface } from '../models/NetworkInterface';
import { ApplicationGateway } from '../models/ApplicationGateway';
import { ApplicationGatewayListResult } from '../models/ApplicationGatewayListResult';
import { ApplicationGatewayBackendHealth } from '../models/ApplicationGatewayBackendHealth';
import { DnsNameAvailabilityResult } from '../models/DnsNameAvailabilityResult';
import { ExpressRouteCircuitAuthorization } from '../models/ExpressRouteCircuitAuthorization';
import { AuthorizationListResult } from '../models/AuthorizationListResult';
import { ExpressRouteCircuitPeering } from '../models/ExpressRouteCircuitPeering';
import { ExpressRouteCircuitPeeringListResult } from '../models/ExpressRouteCircuitPeeringListResult';
import { ExpressRouteCircuit } from '../models/ExpressRouteCircuit';
import { ExpressRouteCircuitsArpTableListResult } from '../models/ExpressRouteCircuitsArpTableListResult';
import { ExpressRouteCircuitsRoutesTableListResult } from '../models/ExpressRouteCircuitsRoutesTableListResult';
import { ExpressRouteCircuitsRoutesTableSummaryListResult } from '../models/ExpressRouteCircuitsRoutesTableSummaryListResult';
import { ExpressRouteCircuitStats } from '../models/ExpressRouteCircuitStats';
import { ExpressRouteCircuitListResult } from '../models/ExpressRouteCircuitListResult';
import { ExpressRouteServiceProviderListResult } from '../models/ExpressRouteServiceProviderListResult';
import { LoadBalancer } from '../models/LoadBalancer';
import { LoadBalancerListResult } from '../models/LoadBalancerListResult';
import { EffectiveRouteListResult } from '../models/EffectiveRouteListResult';
import { EffectiveNetworkSecurityGroupListResult } from '../models/EffectiveNetworkSecurityGroupListResult';
import { NetworkSecurityGroup } from '../models/NetworkSecurityGroup';
import { NetworkSecurityGroupListResult } from '../models/NetworkSecurityGroupListResult';
import { SecurityRule } from '../models/SecurityRule';
import { SecurityRuleListResult } from '../models/SecurityRuleListResult';
import { NetworkWatcher } from '../models/NetworkWatcher';
import { NetworkWatcherListResult } from '../models/NetworkWatcherListResult';
import { TopologyParameters } from '../models/TopologyParameters';
import { Topology } from '../models/Topology';
import { VerificationIPFlowParameters } from '../models/VerificationIPFlowParameters';
import { VerificationIPFlowResult } from '../models/VerificationIPFlowResult';
import { NextHopParameters } from '../models/NextHopParameters';
import { NextHopResult } from '../models/NextHopResult';
import { SecurityGroupViewParameters } from '../models/SecurityGroupViewParameters';
import { SecurityGroupViewResult } from '../models/SecurityGroupViewResult';
import { PacketCaptureResult } from '../models/PacketCaptureResult';
import { PacketCapture } from '../models/PacketCapture';
import { PacketCaptureQueryStatusResult } from '../models/PacketCaptureQueryStatusResult';
import { PacketCaptureListResult } from '../models/PacketCaptureListResult';
import { TroubleshootingParameters } from '../models/TroubleshootingParameters';
import { TroubleshootingResult } from '../models/TroubleshootingResult';
import { QueryTroubleshootingParameters } from '../models/QueryTroubleshootingParameters';
import { FlowLogInformation } from '../models/FlowLogInformation';
import { FlowLogStatusParameters } from '../models/FlowLogStatusParameters';
import { PublicIPAddress } from '../models/PublicIPAddress';
import { PublicIPAddressListResult } from '../models/PublicIPAddressListResult';
import { RouteTable } from '../models/RouteTable';
import { RouteTableListResult } from '../models/RouteTableListResult';
import { Route } from '../models/Route';
import { RouteListResult } from '../models/RouteListResult';
import { UsagesListResult } from '../models/UsagesListResult';
import { VirtualNetwork } from '../models/VirtualNetwork';
import { VirtualNetworkListResult } from '../models/VirtualNetworkListResult';
import { Subnet } from '../models/Subnet';
import { SubnetListResult } from '../models/SubnetListResult';
import { VirtualNetworkPeering } from '../models/VirtualNetworkPeering';
import { VirtualNetworkPeeringListResult } from '../models/VirtualNetworkPeeringListResult';
import { IPAddressAvailabilityResult } from '../models/IPAddressAvailabilityResult';
import { VirtualNetworkGateway } from '../models/VirtualNetworkGateway';
import { VirtualNetworkGatewayListResult } from '../models/VirtualNetworkGatewayListResult';
import { VpnClientParameters } from '../models/VpnClientParameters';
import { BgpPeerStatusListResult } from '../models/BgpPeerStatusListResult';
import { GatewayRouteListResult } from '../models/GatewayRouteListResult';
import { VirtualNetworkGatewayConnection } from '../models/VirtualNetworkGatewayConnection';
import { ConnectionSharedKey } from '../models/ConnectionSharedKey';
import { VirtualNetworkGatewayConnectionListResult } from '../models/VirtualNetworkGatewayConnectionListResult';
import { ConnectionResetSharedKey } from '../models/ConnectionResetSharedKey';
import { LocalNetworkGateway } from '../models/LocalNetworkGateway';
import { LocalNetworkGatewayListResult } from '../models/LocalNetworkGatewayListResult';
export type schema = NetworkInterfaceListResult;
export type schema = NetworkInterfaceListResult;
export type schema = NetworkInterfaceListResult;
export type schema = NetworkInterfaceListResult;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = ApplicationGateway;
export type schema = ApplicationGateway;
export type schema = ApplicationGateway;
export type schema = ApplicationGateway;
export type schema = ApplicationGateway;
export type schema = ApplicationGateway;
export type schema = ApplicationGateway;
export type schema = ApplicationGateway;
export type schema = ApplicationGatewayListResult;
export type schema = ApplicationGatewayListResult;
export type schema = ApplicationGatewayListResult;
export type schema = ApplicationGatewayListResult;
export type schema = ApplicationGatewayBackendHealth;
export type schema = ApplicationGatewayBackendHealth;
export type schema = DnsNameAvailabilityResult;
export type schema = DnsNameAvailabilityResult;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = AuthorizationListResult;
export type schema = AuthorizationListResult;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeeringListResult;
export type schema = ExpressRouteCircuitPeeringListResult;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuitsArpTableListResult;
export type schema = ExpressRouteCircuitsArpTableListResult;
export type schema = ExpressRouteCircuitsRoutesTableListResult;
export type schema = ExpressRouteCircuitsRoutesTableListResult;
export type schema = ExpressRouteCircuitsRoutesTableSummaryListResult;
export type schema = ExpressRouteCircuitsRoutesTableSummaryListResult;
export type schema = ExpressRouteCircuitStats;
export type schema = ExpressRouteCircuitStats;
export type schema = ExpressRouteCircuitStats;
export type schema = ExpressRouteCircuitStats;
export type schema = ExpressRouteCircuitListResult;
export type schema = ExpressRouteCircuitListResult;
export type schema = ExpressRouteCircuitListResult;
export type schema = ExpressRouteCircuitListResult;
export type schema = ExpressRouteServiceProviderListResult;
export type schema = ExpressRouteServiceProviderListResult;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = LoadBalancerListResult;
export type schema = LoadBalancerListResult;
export type schema = LoadBalancerListResult;
export type schema = LoadBalancerListResult;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterfaceListResult;
export type schema = NetworkInterfaceListResult;
export type schema = NetworkInterfaceListResult;
export type schema = NetworkInterfaceListResult;
export type schema = EffectiveRouteListResult;
export type schema = EffectiveRouteListResult;
export type schema = EffectiveNetworkSecurityGroupListResult;
export type schema = EffectiveNetworkSecurityGroupListResult;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroupListResult;
export type schema = NetworkSecurityGroupListResult;
export type schema = NetworkSecurityGroupListResult;
export type schema = NetworkSecurityGroupListResult;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = SecurityRuleListResult;
export type schema = SecurityRuleListResult;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = NetworkWatcherListResult;
export type schema = NetworkWatcherListResult;
export type schema = NetworkWatcherListResult;
export type schema = NetworkWatcherListResult;
export type schema = TopologyParameters;
export type schema = TopologyParameters;
export type schema = Topology;
export type schema = Topology;
export type schema = VerificationIPFlowParameters;
export type schema = VerificationIPFlowParameters;
export type schema = VerificationIPFlowResult;
export type schema = VerificationIPFlowResult;
export type schema = VerificationIPFlowResult;
export type schema = VerificationIPFlowResult;
export type schema = NextHopParameters;
export type schema = NextHopParameters;
export type schema = NextHopResult;
export type schema = NextHopResult;
export type schema = NextHopResult;
export type schema = NextHopResult;
export type schema = SecurityGroupViewParameters;
export type schema = SecurityGroupViewParameters;
export type schema = SecurityGroupViewResult;
export type schema = SecurityGroupViewResult;
export type schema = SecurityGroupViewResult;
export type schema = SecurityGroupViewResult;
export type schema = PacketCaptureResult;
export type schema = PacketCaptureResult;
export type schema = PacketCapture;
export type schema = PacketCapture;
export type schema = PacketCaptureResult;
export type schema = PacketCaptureResult;
export type schema = PacketCaptureQueryStatusResult;
export type schema = PacketCaptureQueryStatusResult;
export type schema = PacketCaptureQueryStatusResult;
export type schema = PacketCaptureQueryStatusResult;
export type schema = PacketCaptureListResult;
export type schema = PacketCaptureListResult;
export type schema = TroubleshootingParameters;
export type schema = TroubleshootingParameters;
export type schema = TroubleshootingResult;
export type schema = TroubleshootingResult;
export type schema = TroubleshootingResult;
export type schema = TroubleshootingResult;
export type schema = QueryTroubleshootingParameters;
export type schema = QueryTroubleshootingParameters;
export type schema = TroubleshootingResult;
export type schema = TroubleshootingResult;
export type schema = TroubleshootingResult;
export type schema = TroubleshootingResult;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = FlowLogStatusParameters;
export type schema = FlowLogStatusParameters;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = PublicIPAddressListResult;
export type schema = PublicIPAddressListResult;
export type schema = PublicIPAddressListResult;
export type schema = PublicIPAddressListResult;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = RouteTableListResult;
export type schema = RouteTableListResult;
export type schema = RouteTableListResult;
export type schema = RouteTableListResult;
export type schema = Route;
export type schema = Route;
export type schema = Route;
export type schema = Route;
export type schema = Route;
export type schema = Route;
export type schema = Route;
export type schema = Route;
export type schema = RouteListResult;
export type schema = RouteListResult;
export type schema = UsagesListResult;
export type schema = UsagesListResult;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = VirtualNetworkListResult;
export type schema = VirtualNetworkListResult;
export type schema = VirtualNetworkListResult;
export type schema = VirtualNetworkListResult;
export type schema = Subnet;
export type schema = Subnet;
export type schema = Subnet;
export type schema = Subnet;
export type schema = Subnet;
export type schema = Subnet;
export type schema = Subnet;
export type schema = Subnet;
export type schema = SubnetListResult;
export type schema = SubnetListResult;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeeringListResult;
export type schema = VirtualNetworkPeeringListResult;
export type schema = IPAddressAvailabilityResult;
export type schema = IPAddressAvailabilityResult;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGatewayListResult;
export type schema = VirtualNetworkGatewayListResult;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VpnClientParameters;
export type schema = VpnClientParameters;
export type schema = BgpPeerStatusListResult;
export type schema = BgpPeerStatusListResult;
export type schema = GatewayRouteListResult;
export type schema = GatewayRouteListResult;
export type schema = GatewayRouteListResult;
export type schema = GatewayRouteListResult;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = VirtualNetworkGatewayConnectionListResult;
export type schema = VirtualNetworkGatewayConnectionListResult;
export type schema = ConnectionResetSharedKey;
export type schema = ConnectionResetSharedKey;
export type schema = ConnectionResetSharedKey;
export type schema = ConnectionResetSharedKey;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGatewayListResult;
export type schema = LocalNetworkGatewayListResult;
