import { ComputeOperationListResult } from '../models/ComputeOperationListResult';
import { AvailabilitySet } from '../models/AvailabilitySet';
import { AvailabilitySetUpdate } from '../models/AvailabilitySetUpdate';
import { AvailabilitySetListResult } from '../models/AvailabilitySetListResult';
import { VirtualMachineSizeListResult } from '../models/VirtualMachineSizeListResult';
import { ProximityPlacementGroup } from '../models/ProximityPlacementGroup';
import { ProximityPlacementGroupUpdate } from '../models/ProximityPlacementGroupUpdate';
import { ProximityPlacementGroupListResult } from '../models/ProximityPlacementGroupListResult';
import { DedicatedHostGroup } from '../models/DedicatedHostGroup';
import { DedicatedHostGroupUpdate } from '../models/DedicatedHostGroupUpdate';
import { DedicatedHostGroupListResult } from '../models/DedicatedHostGroupListResult';
import { DedicatedHost } from '../models/DedicatedHost';
import { DedicatedHostUpdate } from '../models/DedicatedHostUpdate';
import { DedicatedHostListResult } from '../models/DedicatedHostListResult';
import { SshPublicKeysGroupListResult } from '../models/SshPublicKeysGroupListResult';
import { SshPublicKeyResource } from '../models/SshPublicKeyResource';
import { SshPublicKeyUpdateResource } from '../models/SshPublicKeyUpdateResource';
import { SshPublicKeyGenerateKeyPairResult } from '../models/SshPublicKeyGenerateKeyPairResult';
import { VirtualMachineExtensionImage } from '../models/VirtualMachineExtensionImage';
import { VirtualMachineExtension } from '../models/VirtualMachineExtension';
import { VirtualMachineExtensionUpdate } from '../models/VirtualMachineExtensionUpdate';
import { VirtualMachineExtensionsListResult } from '../models/VirtualMachineExtensionsListResult';
import { VirtualMachineImage } from '../models/VirtualMachineImage';
import { ListUsagesResult } from '../models/ListUsagesResult';
import { VirtualMachineListResult } from '../models/VirtualMachineListResult';
import { Image } from '../models/Image';
import { ImageUpdate } from '../models/ImageUpdate';
import { ImageListResult } from '../models/ImageListResult';
import { VirtualMachineCaptureParameters } from '../models/VirtualMachineCaptureParameters';
import { VirtualMachineCaptureResult } from '../models/VirtualMachineCaptureResult';
import { VirtualMachine } from '../models/VirtualMachine';
import { VirtualMachineUpdate } from '../models/VirtualMachineUpdate';
import { VirtualMachineInstanceView } from '../models/VirtualMachineInstanceView';
import { CloudError } from '../models/CloudError';
import { VirtualMachineReimageParameters } from '../models/VirtualMachineReimageParameters';
import { VirtualMachineScaleSet } from '../models/VirtualMachineScaleSet';
import { VirtualMachineScaleSetUpdate } from '../models/VirtualMachineScaleSetUpdate';
import { VirtualMachineScaleSetVMInstanceIDs } from '../models/VirtualMachineScaleSetVMInstanceIDs';
import { VirtualMachineScaleSetVMInstanceRequiredIDs } from '../models/VirtualMachineScaleSetVMInstanceRequiredIDs';
import { VirtualMachineScaleSetInstanceView } from '../models/VirtualMachineScaleSetInstanceView';
import { VirtualMachineScaleSetListResult } from '../models/VirtualMachineScaleSetListResult';
import { VirtualMachineScaleSetExtension } from '../models/VirtualMachineScaleSetExtension';
import { VirtualMachineScaleSetExtensionUpdate } from '../models/VirtualMachineScaleSetExtensionUpdate';
import { VirtualMachineScaleSetExtensionListResult } from '../models/VirtualMachineScaleSetExtensionListResult';
import { VirtualMachineScaleSetListWithLinkResult } from '../models/VirtualMachineScaleSetListWithLinkResult';
import { VirtualMachineScaleSetListSkusResult } from '../models/VirtualMachineScaleSetListSkusResult';
import { VirtualMachineScaleSetListOSUpgradeHistory } from '../models/VirtualMachineScaleSetListOSUpgradeHistory';
import { VirtualMachineScaleSetReimageParameters } from '../models/VirtualMachineScaleSetReimageParameters';
import { RollingUpgradeStatusInfo } from '../models/RollingUpgradeStatusInfo';
import { RecoveryWalkResponse } from '../models/RecoveryWalkResponse';
import { VMScaleSetConvertToSinglePlacementGroupInput } from '../models/VMScaleSetConvertToSinglePlacementGroupInput';
import { OrchestrationServiceStateInput } from '../models/OrchestrationServiceStateInput';
import { VirtualMachineScaleSetVMReimageParameters } from '../models/VirtualMachineScaleSetVMReimageParameters';
import { VirtualMachineScaleSetVM } from '../models/VirtualMachineScaleSetVM';
import { VirtualMachineScaleSetVMInstanceView } from '../models/VirtualMachineScaleSetVMInstanceView';
import { VirtualMachineScaleSetVMListResult } from '../models/VirtualMachineScaleSetVMListResult';
import { RequestRateByIntervalInput } from '../models/RequestRateByIntervalInput';
import { LogAnalyticsOperationResult } from '../models/LogAnalyticsOperationResult';
import { ThrottledRequestsInput } from '../models/ThrottledRequestsInput';
import { RunCommandListResult } from '../models/RunCommandListResult';
import { RunCommandDocument } from '../models/RunCommandDocument';
import { RunCommandInput } from '../models/RunCommandInput';
import { RunCommandResult } from '../models/RunCommandResult';
import { ResourceSkusResult } from '../models/ResourceSkusResult';
import { Disk } from '../models/Disk';
import { DiskUpdate } from '../models/DiskUpdate';
import { DiskList } from '../models/DiskList';
import { GrantAccessData } from '../models/GrantAccessData';
import { AccessUri } from '../models/AccessUri';
import { Snapshot } from '../models/Snapshot';
import { SnapshotUpdate } from '../models/SnapshotUpdate';
import { SnapshotList } from '../models/SnapshotList';
import { DiskEncryptionSet } from '../models/DiskEncryptionSet';
import { DiskEncryptionSetUpdate } from '../models/DiskEncryptionSetUpdate';
import { DiskEncryptionSetList } from '../models/DiskEncryptionSetList';
import { Gallery } from '../models/Gallery';
import { GalleryUpdate } from '../models/GalleryUpdate';
import { GalleryImage } from '../models/GalleryImage';
import { GalleryImageUpdate } from '../models/GalleryImageUpdate';
import { GalleryImageVersion } from '../models/GalleryImageVersion';
import { GalleryImageVersionUpdate } from '../models/GalleryImageVersionUpdate';
import { GalleryApplication } from '../models/GalleryApplication';
import { GalleryApplicationUpdate } from '../models/GalleryApplicationUpdate';
import { GalleryApplicationVersion } from '../models/GalleryApplicationVersion';
import { GalleryApplicationVersionUpdate } from '../models/GalleryApplicationVersionUpdate';
import { GalleryList } from '../models/GalleryList';
import { GalleryImageList } from '../models/GalleryImageList';
import { GalleryImageVersionList } from '../models/GalleryImageVersionList';
import { GalleryApplicationList } from '../models/GalleryApplicationList';
import { GalleryApplicationVersionList } from '../models/GalleryApplicationVersionList';
export type schema = ComputeOperationListResult;
export type schema = AvailabilitySet;
export type schema = AvailabilitySet;
export type schema = AvailabilitySet;
export type schema = AvailabilitySetUpdate;
export type schema = AvailabilitySet;
export type schema = AvailabilitySetListResult;
export type schema = AvailabilitySetListResult;
export type schema = VirtualMachineSizeListResult;
export type schema = ProximityPlacementGroup;
export type schema = ProximityPlacementGroup;
export type schema = ProximityPlacementGroup;
export type schema = ProximityPlacementGroup;
export type schema = ProximityPlacementGroupUpdate;
export type schema = ProximityPlacementGroup;
export type schema = ProximityPlacementGroupListResult;
export type schema = ProximityPlacementGroupListResult;
export type schema = DedicatedHostGroup;
export type schema = DedicatedHostGroup;
export type schema = DedicatedHostGroup;
export type schema = DedicatedHostGroup;
export type schema = DedicatedHostGroupUpdate;
export type schema = DedicatedHostGroup;
export type schema = DedicatedHostGroupListResult;
export type schema = DedicatedHostGroupListResult;
export type schema = DedicatedHost;
export type schema = DedicatedHost;
export type schema = DedicatedHost;
export type schema = DedicatedHost;
export type schema = DedicatedHostUpdate;
export type schema = DedicatedHost;
export type schema = DedicatedHostListResult;
export type schema = SshPublicKeysGroupListResult;
export type schema = SshPublicKeysGroupListResult;
export type schema = SshPublicKeyResource;
export type schema = SshPublicKeyResource;
export type schema = SshPublicKeyResource;
export type schema = SshPublicKeyResource;
export type schema = SshPublicKeyUpdateResource;
export type schema = SshPublicKeyResource;
export type schema = SshPublicKeyGenerateKeyPairResult;
export type schema = VirtualMachineExtensionImage;
export type schema = VirtualMachineExtension;
export type schema = VirtualMachineExtension;
export type schema = VirtualMachineExtension;
export type schema = VirtualMachineExtension;
export type schema = VirtualMachineExtensionUpdate;
export type schema = VirtualMachineExtension;
export type schema = VirtualMachineExtensionsListResult;
export type schema = VirtualMachineImage;
export type schema = ListUsagesResult;
export type schema = VirtualMachineListResult;
export type schema = VirtualMachineSizeListResult;
export type schema = Image;
export type schema = Image;
export type schema = Image;
export type schema = Image;
export type schema = ImageUpdate;
export type schema = Image;
export type schema = Image;
export type schema = ImageListResult;
export type schema = ImageListResult;
export type schema = VirtualMachineCaptureParameters;
export type schema = VirtualMachineCaptureResult;
export type schema = VirtualMachine;
export type schema = VirtualMachine;
export type schema = VirtualMachine;
export type schema = VirtualMachine;
export type schema = VirtualMachineUpdate;
export type schema = VirtualMachine;
export type schema = VirtualMachine;
export type schema = VirtualMachineInstanceView;
export type schema = VirtualMachineListResult;
export type schema = VirtualMachineListResult;
export type schema = VirtualMachineSizeListResult;
export type schema = CloudError;
export type schema = VirtualMachineReimageParameters;
export type schema = VirtualMachineScaleSet;
export type schema = VirtualMachineScaleSet;
export type schema = VirtualMachineScaleSet;
export type schema = VirtualMachineScaleSet;
export type schema = VirtualMachineScaleSetUpdate;
export type schema = VirtualMachineScaleSet;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = VirtualMachineScaleSetVMInstanceRequiredIDs;
export type schema = VirtualMachineScaleSetInstanceView;
export type schema = VirtualMachineScaleSetListResult;
export type schema = VirtualMachineScaleSetExtension;
export type schema = VirtualMachineScaleSetExtension;
export type schema = VirtualMachineScaleSetExtension;
export type schema = VirtualMachineScaleSetExtension;
export type schema = VirtualMachineScaleSetExtensionUpdate;
export type schema = VirtualMachineScaleSetExtension;
export type schema = VirtualMachineScaleSetExtension;
export type schema = VirtualMachineScaleSetExtensionListResult;
export type schema = VirtualMachineScaleSetListWithLinkResult;
export type schema = VirtualMachineScaleSetListSkusResult;
export type schema = VirtualMachineScaleSetListOSUpgradeHistory;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = VirtualMachineScaleSetVMInstanceRequiredIDs;
export type schema = VirtualMachineScaleSetReimageParameters;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = RollingUpgradeStatusInfo;
export type schema = RecoveryWalkResponse;
export type schema = VMScaleSetConvertToSinglePlacementGroupInput;
export type schema = OrchestrationServiceStateInput;
export type schema = VirtualMachineExtension;
export type schema = CloudError;
export type schema = VirtualMachineExtension;
export type schema = VirtualMachineExtension;
export type schema = VirtualMachineExtension;
export type schema = CloudError;
export type schema = CloudError;
export type schema = VirtualMachineExtensionUpdate;
export type schema = VirtualMachineExtension;
export type schema = CloudError;
export type schema = VirtualMachineExtensionsListResult;
export type schema = CloudError;
export type schema = VirtualMachineScaleSetVMReimageParameters;
export type schema = VirtualMachineScaleSetVM;
export type schema = VirtualMachineScaleSetVM;
export type schema = VirtualMachineScaleSetVM;
export type schema = VirtualMachineScaleSetVM;
export type schema = VirtualMachineScaleSetVMInstanceView;
export type schema = VirtualMachineScaleSetVMListResult;
export type schema = RequestRateByIntervalInput;
export type schema = LogAnalyticsOperationResult;
export type schema = ThrottledRequestsInput;
export type schema = LogAnalyticsOperationResult;
export type schema = RunCommandListResult;
export type schema = RunCommandListResult;
export type schema = RunCommandDocument;
export type schema = RunCommandDocument;
export type schema = RunCommandInput;
export type schema = RunCommandInput;
export type schema = RunCommandResult;
export type schema = RunCommandResult;
export type schema = RunCommandInput;
export type schema = RunCommandInput;
export type schema = RunCommandResult;
export type schema = RunCommandResult;
export type schema = ResourceSkusResult;
export type schema = Disk;
export type schema = Disk;
export type schema = Disk;
export type schema = Disk;
export type schema = DiskUpdate;
export type schema = Disk;
export type schema = Disk;
export type schema = DiskList;
export type schema = DiskList;
export type schema = GrantAccessData;
export type schema = AccessUri;
export type schema = Snapshot;
export type schema = Snapshot;
export type schema = Snapshot;
export type schema = Snapshot;
export type schema = SnapshotUpdate;
export type schema = Snapshot;
export type schema = Snapshot;
export type schema = SnapshotList;
export type schema = SnapshotList;
export type schema = GrantAccessData;
export type schema = AccessUri;
export type schema = DiskEncryptionSet;
export type schema = CloudError;
export type schema = DiskEncryptionSet;
export type schema = DiskEncryptionSet;
export type schema = DiskEncryptionSet;
export type schema = CloudError;
export type schema = CloudError;
export type schema = DiskEncryptionSetUpdate;
export type schema = DiskEncryptionSet;
export type schema = DiskEncryptionSet;
export type schema = CloudError;
export type schema = DiskEncryptionSetList;
export type schema = CloudError;
export type schema = DiskEncryptionSetList;
export type schema = CloudError;
export type schema = Gallery;
export type schema = CloudError;
export type schema = Gallery;
export type schema = Gallery;
export type schema = Gallery;
export type schema = Gallery;
export type schema = CloudError;
export type schema = CloudError;
export type schema = GalleryUpdate;
export type schema = Gallery;
export type schema = CloudError;
export type schema = GalleryImage;
export type schema = CloudError;
export type schema = GalleryImage;
export type schema = GalleryImage;
export type schema = GalleryImage;
export type schema = GalleryImage;
export type schema = CloudError;
export type schema = CloudError;
export type schema = GalleryImageUpdate;
export type schema = GalleryImage;
export type schema = CloudError;
export type schema = GalleryImageVersion;
export type schema = CloudError;
export type schema = GalleryImageVersion;
export type schema = GalleryImageVersion;
export type schema = GalleryImageVersion;
export type schema = GalleryImageVersion;
export type schema = CloudError;
export type schema = CloudError;
export type schema = GalleryImageVersionUpdate;
export type schema = GalleryImageVersion;
export type schema = CloudError;
export type schema = GalleryApplication;
export type schema = CloudError;
export type schema = GalleryApplication;
export type schema = GalleryApplication;
export type schema = GalleryApplication;
export type schema = GalleryApplication;
export type schema = CloudError;
export type schema = CloudError;
export type schema = GalleryApplicationUpdate;
export type schema = GalleryApplication;
export type schema = CloudError;
export type schema = GalleryApplicationVersion;
export type schema = CloudError;
export type schema = GalleryApplicationVersion;
export type schema = GalleryApplicationVersion;
export type schema = GalleryApplicationVersion;
export type schema = GalleryApplicationVersion;
export type schema = CloudError;
export type schema = CloudError;
export type schema = GalleryApplicationVersionUpdate;
export type schema = GalleryApplicationVersion;
export type schema = CloudError;
export type schema = GalleryList;
export type schema = CloudError;
export type schema = GalleryList;
export type schema = CloudError;
export type schema = GalleryImageList;
export type schema = CloudError;
export type schema = GalleryImageVersionList;
export type schema = CloudError;
export type schema = GalleryApplicationList;
export type schema = CloudError;
export type schema = GalleryApplicationVersionList;
export type schema = CloudError;
