import { AvailabilitySet } from '../models/AvailabilitySet';
import { OperationStatusResponse } from '../models/OperationStatusResponse';
import { AvailabilitySetListResult } from '../models/AvailabilitySetListResult';
import { VirtualMachineSizeListResult } from '../models/VirtualMachineSizeListResult';
import { VirtualMachineExtensionImage } from '../models/VirtualMachineExtensionImage';
import { VirtualMachineExtension } from '../models/VirtualMachineExtension';
import { VirtualMachineExtensionUpdate } from '../models/VirtualMachineExtensionUpdate';
import { VirtualMachineExtensionsListResult } from '../models/VirtualMachineExtensionsListResult';
import { VirtualMachineImage } from '../models/VirtualMachineImage';
import { ListUsagesResult } from '../models/ListUsagesResult';
import { VirtualMachineListResult } from '../models/VirtualMachineListResult';
import { Image } from '../models/Image';
import { ImageListResult } from '../models/ImageListResult';
import { ResourceSkusResult } from '../models/ResourceSkusResult';
import { VirtualMachineCaptureParameters } from '../models/VirtualMachineCaptureParameters';
import { VirtualMachineCaptureResult } from '../models/VirtualMachineCaptureResult';
import { VirtualMachine } from '../models/VirtualMachine';
import { VirtualMachineInstanceView } from '../models/VirtualMachineInstanceView';
import { VirtualMachineScaleSet } from '../models/VirtualMachineScaleSet';
import { VirtualMachineScaleSetUpdate } from '../models/VirtualMachineScaleSetUpdate';
import { VirtualMachineScaleSetVMInstanceIDs } from '../models/VirtualMachineScaleSetVMInstanceIDs';
import { VirtualMachineScaleSetVMInstanceRequiredIDs } from '../models/VirtualMachineScaleSetVMInstanceRequiredIDs';
import { VirtualMachineScaleSetInstanceView } from '../models/VirtualMachineScaleSetInstanceView';
import { VirtualMachineScaleSetListResult } from '../models/VirtualMachineScaleSetListResult';
import { VirtualMachineScaleSetExtension } from '../models/VirtualMachineScaleSetExtension';
import { VirtualMachineScaleSetExtensionListResult } from '../models/VirtualMachineScaleSetExtensionListResult';
import { VirtualMachineScaleSetListWithLinkResult } from '../models/VirtualMachineScaleSetListWithLinkResult';
import { VirtualMachineScaleSetListSkusResult } from '../models/VirtualMachineScaleSetListSkusResult';
import { RollingUpgradeStatusInfo } from '../models/RollingUpgradeStatusInfo';
import { VirtualMachineScaleSetVM } from '../models/VirtualMachineScaleSetVM';
import { VirtualMachineScaleSetVMInstanceView } from '../models/VirtualMachineScaleSetVMInstanceView';
import { VirtualMachineScaleSetVMListResult } from '../models/VirtualMachineScaleSetVMListResult';
import { Disk } from '../models/Disk';
import { DiskUpdate } from '../models/DiskUpdate';
import { DiskList } from '../models/DiskList';
import { GrantAccessData } from '../models/GrantAccessData';
import { AccessUri } from '../models/AccessUri';
import { Snapshot } from '../models/Snapshot';
import { SnapshotUpdate } from '../models/SnapshotUpdate';
import { SnapshotList } from '../models/SnapshotList';
import { RunCommandListResult } from '../models/RunCommandListResult';
import { RunCommandDocument } from '../models/RunCommandDocument';
import { RunCommandInput } from '../models/RunCommandInput';
import { RunCommandResult } from '../models/RunCommandResult';
export type schema = AvailabilitySet;
export type schema = AvailabilitySet;
export type schema = AvailabilitySet;
export type schema = OperationStatusResponse;
export type schema = AvailabilitySetListResult;
export type schema = AvailabilitySetListResult;
export type schema = VirtualMachineSizeListResult;
export type schema = VirtualMachineExtensionImage;
export type schema = VirtualMachineExtension;
export type schema = VirtualMachineExtension;
export type schema = VirtualMachineExtension;
export type schema = VirtualMachineExtension;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineExtensionUpdate;
export type schema = VirtualMachineExtension;
export type schema = VirtualMachineExtensionsListResult;
export type schema = VirtualMachineImage;
export type schema = ListUsagesResult;
export type schema = VirtualMachineListResult;
export type schema = VirtualMachineSizeListResult;
export type schema = Image;
export type schema = Image;
export type schema = Image;
export type schema = Image;
export type schema = OperationStatusResponse;
export type schema = ImageListResult;
export type schema = ImageListResult;
export type schema = ResourceSkusResult;
export type schema = VirtualMachineCaptureParameters;
export type schema = VirtualMachineCaptureResult;
export type schema = VirtualMachine;
export type schema = VirtualMachine;
export type schema = VirtualMachine;
export type schema = VirtualMachine;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineInstanceView;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineListResult;
export type schema = VirtualMachineListResult;
export type schema = VirtualMachineSizeListResult;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSet;
export type schema = VirtualMachineScaleSet;
export type schema = VirtualMachineScaleSet;
export type schema = VirtualMachineScaleSet;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetUpdate;
export type schema = VirtualMachineScaleSet;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetVMInstanceRequiredIDs;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetInstanceView;
export type schema = VirtualMachineScaleSetListResult;
export type schema = VirtualMachineScaleSetExtension;
export type schema = VirtualMachineScaleSetExtension;
export type schema = VirtualMachineScaleSetExtension;
export type schema = VirtualMachineScaleSetExtension;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetExtensionListResult;
export type schema = VirtualMachineScaleSetListWithLinkResult;
export type schema = VirtualMachineScaleSetListSkusResult;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetVMInstanceRequiredIDs;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = RollingUpgradeStatusInfo;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetVM;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetVMInstanceView;
export type schema = VirtualMachineScaleSetVMListResult;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = Disk;
export type schema = Disk;
export type schema = Disk;
export type schema = Disk;
export type schema = OperationStatusResponse;
export type schema = DiskUpdate;
export type schema = Disk;
export type schema = Disk;
export type schema = DiskList;
export type schema = DiskList;
export type schema = GrantAccessData;
export type schema = AccessUri;
export type schema = OperationStatusResponse;
export type schema = Snapshot;
export type schema = Snapshot;
export type schema = Snapshot;
export type schema = Snapshot;
export type schema = OperationStatusResponse;
export type schema = SnapshotUpdate;
export type schema = Snapshot;
export type schema = Snapshot;
export type schema = SnapshotList;
export type schema = SnapshotList;
export type schema = GrantAccessData;
export type schema = AccessUri;
export type schema = OperationStatusResponse;
export type schema = RunCommandListResult;
export type schema = RunCommandListResult;
export type schema = RunCommandDocument;
export type schema = RunCommandDocument;
export type schema = RunCommandInput;
export type schema = RunCommandInput;
export type schema = RunCommandResult;
export type schema = RunCommandResult;
