import { ApplicationGateway } from '../models/ApplicationGateway';
import { TagsObject } from '../models/TagsObject';
import { ApplicationGatewayListResult } from '../models/ApplicationGatewayListResult';
import { ApplicationGatewayBackendHealth } from '../models/ApplicationGatewayBackendHealth';
import { ApplicationGatewayAvailableWafRuleSetsResult } from '../models/ApplicationGatewayAvailableWafRuleSetsResult';
import { ApplicationGatewayAvailableSslOptions } from '../models/ApplicationGatewayAvailableSslOptions';
import { ApplicationGatewayAvailableSslPredefinedPolicies } from '../models/ApplicationGatewayAvailableSslPredefinedPolicies';
import { ApplicationGatewaySslPredefinedPolicy } from '../models/ApplicationGatewaySslPredefinedPolicy';
import { ApplicationSecurityGroup } from '../models/ApplicationSecurityGroup';
import { ApplicationSecurityGroupListResult } from '../models/ApplicationSecurityGroupListResult';
import { DnsNameAvailabilityResult } from '../models/DnsNameAvailabilityResult';
import { EndpointServicesListResult } from '../models/EndpointServicesListResult';
import { ExpressRouteCircuitAuthorization } from '../models/ExpressRouteCircuitAuthorization';
import { AuthorizationListResult } from '../models/AuthorizationListResult';
import { ExpressRouteCircuitPeering } from '../models/ExpressRouteCircuitPeering';
import { ExpressRouteCircuitPeeringListResult } from '../models/ExpressRouteCircuitPeeringListResult';
import { ExpressRouteCircuit } from '../models/ExpressRouteCircuit';
import { ExpressRouteCircuitsArpTableListResult } from '../models/ExpressRouteCircuitsArpTableListResult';
import { ExpressRouteCircuitsRoutesTableListResult } from '../models/ExpressRouteCircuitsRoutesTableListResult';
import { ExpressRouteCircuitsRoutesTableSummaryListResult } from '../models/ExpressRouteCircuitsRoutesTableSummaryListResult';
import { ExpressRouteCircuitStats } from '../models/ExpressRouteCircuitStats';
import { ExpressRouteCircuitListResult } from '../models/ExpressRouteCircuitListResult';
import { ExpressRouteServiceProviderListResult } from '../models/ExpressRouteServiceProviderListResult';
import { LoadBalancer } from '../models/LoadBalancer';
import { LoadBalancerListResult } from '../models/LoadBalancerListResult';
import { LoadBalancerBackendAddressPoolListResult } from '../models/LoadBalancerBackendAddressPoolListResult';
import { BackendAddressPool } from '../models/BackendAddressPool';
import { LoadBalancerFrontendIPConfigurationListResult } from '../models/LoadBalancerFrontendIPConfigurationListResult';
import { FrontendIPConfiguration } from '../models/FrontendIPConfiguration';
import { InboundNatRuleListResult } from '../models/InboundNatRuleListResult';
import { InboundNatRule } from '../models/InboundNatRule';
import { LoadBalancerLoadBalancingRuleListResult } from '../models/LoadBalancerLoadBalancingRuleListResult';
import { LoadBalancingRule } from '../models/LoadBalancingRule';
import { NetworkInterfaceListResult } from '../models/NetworkInterfaceListResult';
import { LoadBalancerProbeListResult } from '../models/LoadBalancerProbeListResult';
import { Probe } from '../models/Probe';
import { NetworkInterface } from '../models/NetworkInterface';
import { EffectiveRouteListResult } from '../models/EffectiveRouteListResult';
import { EffectiveNetworkSecurityGroupListResult } from '../models/EffectiveNetworkSecurityGroupListResult';
import { NetworkInterfaceIPConfigurationListResult } from '../models/NetworkInterfaceIPConfigurationListResult';
import { NetworkInterfaceIPConfiguration } from '../models/NetworkInterfaceIPConfiguration';
import { NetworkInterfaceLoadBalancerListResult } from '../models/NetworkInterfaceLoadBalancerListResult';
import { NetworkSecurityGroup } from '../models/NetworkSecurityGroup';
import { NetworkSecurityGroupListResult } from '../models/NetworkSecurityGroupListResult';
import { SecurityRule } from '../models/SecurityRule';
import { SecurityRuleListResult } from '../models/SecurityRuleListResult';
import { NetworkWatcher } from '../models/NetworkWatcher';
import { NetworkWatcherListResult } from '../models/NetworkWatcherListResult';
import { TopologyParameters } from '../models/TopologyParameters';
import { Topology } from '../models/Topology';
import { VerificationIPFlowParameters } from '../models/VerificationIPFlowParameters';
import { VerificationIPFlowResult } from '../models/VerificationIPFlowResult';
import { NextHopParameters } from '../models/NextHopParameters';
import { NextHopResult } from '../models/NextHopResult';
import { SecurityGroupViewParameters } from '../models/SecurityGroupViewParameters';
import { SecurityGroupViewResult } from '../models/SecurityGroupViewResult';
import { PacketCaptureResult } from '../models/PacketCaptureResult';
import { PacketCapture } from '../models/PacketCapture';
import { PacketCaptureQueryStatusResult } from '../models/PacketCaptureQueryStatusResult';
import { PacketCaptureListResult } from '../models/PacketCaptureListResult';
import { TroubleshootingParameters } from '../models/TroubleshootingParameters';
import { TroubleshootingResult } from '../models/TroubleshootingResult';
import { QueryTroubleshootingParameters } from '../models/QueryTroubleshootingParameters';
import { FlowLogInformation } from '../models/FlowLogInformation';
import { FlowLogStatusParameters } from '../models/FlowLogStatusParameters';
import { ConnectivityParameters } from '../models/ConnectivityParameters';
import { ConnectivityInformation } from '../models/ConnectivityInformation';
import { AzureReachabilityReportParameters } from '../models/AzureReachabilityReportParameters';
import { AzureReachabilityReport } from '../models/AzureReachabilityReport';
import { AvailableProvidersListParameters } from '../models/AvailableProvidersListParameters';
import { AvailableProvidersList } from '../models/AvailableProvidersList';
import { ConnectionMonitorResult } from '../models/ConnectionMonitorResult';
import { ConnectionMonitor } from '../models/ConnectionMonitor';
import { ConnectionMonitorQueryResult } from '../models/ConnectionMonitorQueryResult';
import { ConnectionMonitorListResult } from '../models/ConnectionMonitorListResult';
import { OperationListResult } from '../models/OperationListResult';
import { PublicIPAddress } from '../models/PublicIPAddress';
import { PublicIPAddressListResult } from '../models/PublicIPAddressListResult';
import { RouteFilter } from '../models/RouteFilter';
import { PatchRouteFilter } from '../models/PatchRouteFilter';
import { RouteFilterListResult } from '../models/RouteFilterListResult';
import { RouteFilterRule } from '../models/RouteFilterRule';
import { PatchRouteFilterRule } from '../models/PatchRouteFilterRule';
import { RouteFilterRuleListResult } from '../models/RouteFilterRuleListResult';
import { RouteTable } from '../models/RouteTable';
import { RouteTableListResult } from '../models/RouteTableListResult';
import { Route } from '../models/Route';
import { RouteListResult } from '../models/RouteListResult';
import { BgpServiceCommunityListResult } from '../models/BgpServiceCommunityListResult';
import { UsagesListResult } from '../models/UsagesListResult';
import { VirtualNetwork } from '../models/VirtualNetwork';
import { VirtualNetworkListResult } from '../models/VirtualNetworkListResult';
import { Subnet } from '../models/Subnet';
import { SubnetListResult } from '../models/SubnetListResult';
import { VirtualNetworkPeering } from '../models/VirtualNetworkPeering';
import { VirtualNetworkPeeringListResult } from '../models/VirtualNetworkPeeringListResult';
import { IPAddressAvailabilityResult } from '../models/IPAddressAvailabilityResult';
import { VirtualNetworkListUsageResult } from '../models/VirtualNetworkListUsageResult';
import { VirtualNetworkGateway } from '../models/VirtualNetworkGateway';
import { VirtualNetworkGatewayListResult } from '../models/VirtualNetworkGatewayListResult';
import { VirtualNetworkGatewayListConnectionsResult } from '../models/VirtualNetworkGatewayListConnectionsResult';
import { VpnClientParameters } from '../models/VpnClientParameters';
import { BgpPeerStatusListResult } from '../models/BgpPeerStatusListResult';
import { GatewayRouteListResult } from '../models/GatewayRouteListResult';
import { VpnDeviceScriptParameters } from '../models/VpnDeviceScriptParameters';
import { VirtualNetworkGatewayConnection } from '../models/VirtualNetworkGatewayConnection';
import { VirtualNetworkGatewayConnectionListEntity } from '../models/VirtualNetworkGatewayConnectionListEntity';
import { ConnectionSharedKey } from '../models/ConnectionSharedKey';
import { VirtualNetworkGatewayConnectionListResult } from '../models/VirtualNetworkGatewayConnectionListResult';
import { ConnectionResetSharedKey } from '../models/ConnectionResetSharedKey';
import { LocalNetworkGateway } from '../models/LocalNetworkGateway';
import { LocalNetworkGatewayListResult } from '../models/LocalNetworkGatewayListResult';
export type schema = ApplicationGateway;
export type schema = ApplicationGateway;
export type schema = ApplicationGateway;
export type schema = ApplicationGateway;
export type schema = TagsObject;
export type schema = ApplicationGateway;
export type schema = ApplicationGatewayListResult;
export type schema = ApplicationGatewayListResult;
export type schema = ApplicationGatewayBackendHealth;
export type schema = ApplicationGatewayAvailableWafRuleSetsResult;
export type schema = ApplicationGatewayAvailableSslOptions;
export type schema = ApplicationGatewayAvailableSslPredefinedPolicies;
export type schema = ApplicationGatewaySslPredefinedPolicy;
export type schema = ApplicationSecurityGroup;
export type schema = ApplicationSecurityGroup;
export type schema = ApplicationSecurityGroup;
export type schema = ApplicationSecurityGroup;
export type schema = ApplicationSecurityGroupListResult;
export type schema = ApplicationSecurityGroupListResult;
export type schema = DnsNameAvailabilityResult;
export type schema = DnsNameAvailabilityResult;
export type schema = EndpointServicesListResult;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = ExpressRouteCircuitAuthorization;
export type schema = AuthorizationListResult;
export type schema = AuthorizationListResult;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeering;
export type schema = ExpressRouteCircuitPeeringListResult;
export type schema = ExpressRouteCircuitPeeringListResult;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = TagsObject;
export type schema = TagsObject;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuit;
export type schema = ExpressRouteCircuitsArpTableListResult;
export type schema = ExpressRouteCircuitsArpTableListResult;
export type schema = ExpressRouteCircuitsRoutesTableListResult;
export type schema = ExpressRouteCircuitsRoutesTableListResult;
export type schema = ExpressRouteCircuitsRoutesTableSummaryListResult;
export type schema = ExpressRouteCircuitsRoutesTableSummaryListResult;
export type schema = ExpressRouteCircuitStats;
export type schema = ExpressRouteCircuitStats;
export type schema = ExpressRouteCircuitStats;
export type schema = ExpressRouteCircuitStats;
export type schema = ExpressRouteCircuitListResult;
export type schema = ExpressRouteCircuitListResult;
export type schema = ExpressRouteCircuitListResult;
export type schema = ExpressRouteCircuitListResult;
export type schema = ExpressRouteServiceProviderListResult;
export type schema = ExpressRouteServiceProviderListResult;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = TagsObject;
export type schema = TagsObject;
export type schema = LoadBalancer;
export type schema = LoadBalancer;
export type schema = LoadBalancerListResult;
export type schema = LoadBalancerListResult;
export type schema = LoadBalancerListResult;
export type schema = LoadBalancerListResult;
export type schema = LoadBalancerBackendAddressPoolListResult;
export type schema = LoadBalancerBackendAddressPoolListResult;
export type schema = BackendAddressPool;
export type schema = BackendAddressPool;
export type schema = LoadBalancerFrontendIPConfigurationListResult;
export type schema = LoadBalancerFrontendIPConfigurationListResult;
export type schema = FrontendIPConfiguration;
export type schema = FrontendIPConfiguration;
export type schema = InboundNatRuleListResult;
export type schema = InboundNatRuleListResult;
export type schema = InboundNatRule;
export type schema = InboundNatRule;
export type schema = InboundNatRule;
export type schema = InboundNatRule;
export type schema = InboundNatRule;
export type schema = InboundNatRule;
export type schema = InboundNatRule;
export type schema = InboundNatRule;
export type schema = LoadBalancerLoadBalancingRuleListResult;
export type schema = LoadBalancerLoadBalancingRuleListResult;
export type schema = LoadBalancingRule;
export type schema = LoadBalancingRule;
export type schema = NetworkInterfaceListResult;
export type schema = NetworkInterfaceListResult;
export type schema = LoadBalancerProbeListResult;
export type schema = LoadBalancerProbeListResult;
export type schema = Probe;
export type schema = Probe;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = TagsObject;
export type schema = TagsObject;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterfaceListResult;
export type schema = NetworkInterfaceListResult;
export type schema = NetworkInterfaceListResult;
export type schema = NetworkInterfaceListResult;
export type schema = EffectiveRouteListResult;
export type schema = EffectiveRouteListResult;
export type schema = EffectiveNetworkSecurityGroupListResult;
export type schema = EffectiveNetworkSecurityGroupListResult;
export type schema = NetworkInterfaceIPConfigurationListResult;
export type schema = NetworkInterfaceIPConfigurationListResult;
export type schema = NetworkInterfaceIPConfiguration;
export type schema = NetworkInterfaceIPConfiguration;
export type schema = NetworkInterfaceLoadBalancerListResult;
export type schema = NetworkInterfaceLoadBalancerListResult;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = TagsObject;
export type schema = TagsObject;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroup;
export type schema = NetworkSecurityGroupListResult;
export type schema = NetworkSecurityGroupListResult;
export type schema = NetworkSecurityGroupListResult;
export type schema = NetworkSecurityGroupListResult;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = SecurityRuleListResult;
export type schema = SecurityRuleListResult;
export type schema = SecurityRuleListResult;
export type schema = SecurityRuleListResult;
export type schema = SecurityRule;
export type schema = SecurityRule;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = TagsObject;
export type schema = TagsObject;
export type schema = NetworkWatcher;
export type schema = NetworkWatcher;
export type schema = NetworkWatcherListResult;
export type schema = NetworkWatcherListResult;
export type schema = NetworkWatcherListResult;
export type schema = NetworkWatcherListResult;
export type schema = TopologyParameters;
export type schema = TopologyParameters;
export type schema = Topology;
export type schema = Topology;
export type schema = VerificationIPFlowParameters;
export type schema = VerificationIPFlowParameters;
export type schema = VerificationIPFlowResult;
export type schema = VerificationIPFlowResult;
export type schema = VerificationIPFlowResult;
export type schema = VerificationIPFlowResult;
export type schema = NextHopParameters;
export type schema = NextHopParameters;
export type schema = NextHopResult;
export type schema = NextHopResult;
export type schema = NextHopResult;
export type schema = NextHopResult;
export type schema = SecurityGroupViewParameters;
export type schema = SecurityGroupViewParameters;
export type schema = SecurityGroupViewResult;
export type schema = SecurityGroupViewResult;
export type schema = SecurityGroupViewResult;
export type schema = SecurityGroupViewResult;
export type schema = PacketCaptureResult;
export type schema = PacketCaptureResult;
export type schema = PacketCapture;
export type schema = PacketCapture;
export type schema = PacketCaptureResult;
export type schema = PacketCaptureResult;
export type schema = PacketCaptureQueryStatusResult;
export type schema = PacketCaptureQueryStatusResult;
export type schema = PacketCaptureQueryStatusResult;
export type schema = PacketCaptureQueryStatusResult;
export type schema = PacketCaptureListResult;
export type schema = PacketCaptureListResult;
export type schema = TroubleshootingParameters;
export type schema = TroubleshootingParameters;
export type schema = TroubleshootingResult;
export type schema = TroubleshootingResult;
export type schema = TroubleshootingResult;
export type schema = TroubleshootingResult;
export type schema = QueryTroubleshootingParameters;
export type schema = QueryTroubleshootingParameters;
export type schema = TroubleshootingResult;
export type schema = TroubleshootingResult;
export type schema = TroubleshootingResult;
export type schema = TroubleshootingResult;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = FlowLogStatusParameters;
export type schema = FlowLogStatusParameters;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = FlowLogInformation;
export type schema = ConnectivityParameters;
export type schema = ConnectivityParameters;
export type schema = ConnectivityInformation;
export type schema = ConnectivityInformation;
export type schema = ConnectivityInformation;
export type schema = ConnectivityInformation;
export type schema = AzureReachabilityReportParameters;
export type schema = AzureReachabilityReportParameters;
export type schema = AzureReachabilityReport;
export type schema = AzureReachabilityReport;
export type schema = AzureReachabilityReport;
export type schema = AzureReachabilityReport;
export type schema = AvailableProvidersListParameters;
export type schema = AvailableProvidersListParameters;
export type schema = AvailableProvidersList;
export type schema = AvailableProvidersList;
export type schema = AvailableProvidersList;
export type schema = AvailableProvidersList;
export type schema = ConnectionMonitorResult;
export type schema = ConnectionMonitorResult;
export type schema = ConnectionMonitor;
export type schema = ConnectionMonitor;
export type schema = ConnectionMonitorResult;
export type schema = ConnectionMonitorResult;
export type schema = ConnectionMonitorResult;
export type schema = ConnectionMonitorResult;
export type schema = ConnectionMonitorQueryResult;
export type schema = ConnectionMonitorQueryResult;
export type schema = ConnectionMonitorQueryResult;
export type schema = ConnectionMonitorQueryResult;
export type schema = ConnectionMonitorListResult;
export type schema = ConnectionMonitorListResult;
export type schema = OperationListResult;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = TagsObject;
export type schema = TagsObject;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
export type schema = PublicIPAddressListResult;
export type schema = PublicIPAddressListResult;
export type schema = PublicIPAddressListResult;
export type schema = PublicIPAddressListResult;
export type schema = RouteFilter;
export type schema = RouteFilter;
export type schema = RouteFilter;
export type schema = RouteFilter;
export type schema = PatchRouteFilter;
export type schema = RouteFilter;
export type schema = RouteFilterListResult;
export type schema = RouteFilterListResult;
export type schema = RouteFilterRule;
export type schema = RouteFilterRule;
export type schema = RouteFilterRule;
export type schema = RouteFilterRule;
export type schema = PatchRouteFilterRule;
export type schema = RouteFilterRule;
export type schema = RouteFilterRuleListResult;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = TagsObject;
export type schema = TagsObject;
export type schema = RouteTable;
export type schema = RouteTable;
export type schema = RouteTableListResult;
export type schema = RouteTableListResult;
export type schema = RouteTableListResult;
export type schema = RouteTableListResult;
export type schema = Route;
export type schema = Route;
export type schema = Route;
export type schema = Route;
export type schema = Route;
export type schema = Route;
export type schema = Route;
export type schema = Route;
export type schema = RouteListResult;
export type schema = RouteListResult;
export type schema = BgpServiceCommunityListResult;
export type schema = UsagesListResult;
export type schema = UsagesListResult;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = TagsObject;
export type schema = TagsObject;
export type schema = VirtualNetwork;
export type schema = VirtualNetwork;
export type schema = VirtualNetworkListResult;
export type schema = VirtualNetworkListResult;
export type schema = VirtualNetworkListResult;
export type schema = VirtualNetworkListResult;
export type schema = Subnet;
export type schema = Subnet;
export type schema = Subnet;
export type schema = Subnet;
export type schema = Subnet;
export type schema = Subnet;
export type schema = Subnet;
export type schema = Subnet;
export type schema = SubnetListResult;
export type schema = SubnetListResult;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeering;
export type schema = VirtualNetworkPeeringListResult;
export type schema = VirtualNetworkPeeringListResult;
export type schema = IPAddressAvailabilityResult;
export type schema = IPAddressAvailabilityResult;
export type schema = VirtualNetworkListUsageResult;
export type schema = VirtualNetworkListUsageResult;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = TagsObject;
export type schema = TagsObject;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGatewayListResult;
export type schema = VirtualNetworkGatewayListResult;
export type schema = VirtualNetworkGatewayListConnectionsResult;
export type schema = VirtualNetworkGatewayListConnectionsResult;
export type schema = VirtualNetworkGateway;
export type schema = VirtualNetworkGateway;
export type schema = VpnClientParameters;
export type schema = VpnClientParameters;
export type schema = VpnClientParameters;
export type schema = VpnClientParameters;
export type schema = BgpPeerStatusListResult;
export type schema = BgpPeerStatusListResult;
export type schema = GatewayRouteListResult;
export type schema = GatewayRouteListResult;
export type schema = GatewayRouteListResult;
export type schema = GatewayRouteListResult;
export type schema = VpnDeviceScriptParameters;
export type schema = VpnDeviceScriptParameters;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = VirtualNetworkGatewayConnection;
export type schema = TagsObject;
export type schema = TagsObject;
export type schema = VirtualNetworkGatewayConnectionListEntity;
export type schema = VirtualNetworkGatewayConnectionListEntity;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = ConnectionSharedKey;
export type schema = VirtualNetworkGatewayConnectionListResult;
export type schema = VirtualNetworkGatewayConnectionListResult;
export type schema = ConnectionResetSharedKey;
export type schema = ConnectionResetSharedKey;
export type schema = ConnectionResetSharedKey;
export type schema = ConnectionResetSharedKey;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = TagsObject;
export type schema = TagsObject;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGateway;
export type schema = LocalNetworkGatewayListResult;
export type schema = LocalNetworkGatewayListResult;
export type schema = NetworkInterfaceListResult;
export type schema = NetworkInterfaceListResult;
export type schema = NetworkInterfaceListResult;
export type schema = NetworkInterfaceListResult;
export type schema = NetworkInterface;
export type schema = NetworkInterface;
export type schema = NetworkInterfaceIPConfigurationListResult;
export type schema = NetworkInterfaceIPConfigurationListResult;
export type schema = NetworkInterfaceIPConfiguration;
export type schema = NetworkInterfaceIPConfiguration;
export type schema = PublicIPAddressListResult;
export type schema = PublicIPAddressListResult;
export type schema = PublicIPAddressListResult;
export type schema = PublicIPAddressListResult;
export type schema = PublicIPAddress;
export type schema = PublicIPAddress;
