import { AvailabilitySet } from '../models/AvailabilitySet';
import { OperationStatusResponse } from '../models/OperationStatusResponse';
import { AvailabilitySetListResult } from '../models/AvailabilitySetListResult';
import { VirtualMachineSizeListResult } from '../models/VirtualMachineSizeListResult';
import { VirtualMachineExtensionImage } from '../models/VirtualMachineExtensionImage';
import { VirtualMachineExtension } from '../models/VirtualMachineExtension';
import { VirtualMachineExtensionUpdate } from '../models/VirtualMachineExtensionUpdate';
import { VirtualMachineImage } from '../models/VirtualMachineImage';
import { ListUsagesResult } from '../models/ListUsagesResult';
import { VirtualMachineCaptureParameters } from '../models/VirtualMachineCaptureParameters';
import { VirtualMachineCaptureResult } from '../models/VirtualMachineCaptureResult';
import { VirtualMachine } from '../models/VirtualMachine';
import { VirtualMachineListResult } from '../models/VirtualMachineListResult';
import { VirtualMachineScaleSet } from '../models/VirtualMachineScaleSet';
import { VirtualMachineScaleSetVMInstanceIDs } from '../models/VirtualMachineScaleSetVMInstanceIDs';
import { VirtualMachineScaleSetVMInstanceRequiredIDs } from '../models/VirtualMachineScaleSetVMInstanceRequiredIDs';
import { VirtualMachineScaleSetInstanceView } from '../models/VirtualMachineScaleSetInstanceView';
import { VirtualMachineScaleSetListResult } from '../models/VirtualMachineScaleSetListResult';
import { VirtualMachineScaleSetListWithLinkResult } from '../models/VirtualMachineScaleSetListWithLinkResult';
import { VirtualMachineScaleSetListSkusResult } from '../models/VirtualMachineScaleSetListSkusResult';
import { VirtualMachineScaleSetVM } from '../models/VirtualMachineScaleSetVM';
import { VirtualMachineScaleSetVMInstanceView } from '../models/VirtualMachineScaleSetVMInstanceView';
import { VirtualMachineScaleSetVMListResult } from '../models/VirtualMachineScaleSetVMListResult';
export type schema = AvailabilitySet;
export type schema = AvailabilitySet;
export type schema = AvailabilitySet;
export type schema = OperationStatusResponse;
export type schema = AvailabilitySetListResult;
export type schema = VirtualMachineSizeListResult;
export type schema = VirtualMachineExtensionImage;
export type schema = VirtualMachineExtension;
export type schema = VirtualMachineExtension;
export type schema = VirtualMachineExtension;
export type schema = VirtualMachineExtension;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineExtensionUpdate;
export type schema = VirtualMachineExtension;
export type schema = VirtualMachineImage;
export type schema = ListUsagesResult;
export type schema = VirtualMachineSizeListResult;
export type schema = VirtualMachineCaptureParameters;
export type schema = VirtualMachineCaptureResult;
export type schema = VirtualMachine;
export type schema = VirtualMachine;
export type schema = VirtualMachine;
export type schema = VirtualMachine;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineListResult;
export type schema = VirtualMachineListResult;
export type schema = VirtualMachineSizeListResult;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSet;
export type schema = VirtualMachineScaleSet;
export type schema = VirtualMachineScaleSet;
export type schema = VirtualMachineScaleSet;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetVMInstanceRequiredIDs;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetInstanceView;
export type schema = VirtualMachineScaleSetListResult;
export type schema = VirtualMachineScaleSetListWithLinkResult;
export type schema = VirtualMachineScaleSetListSkusResult;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetVMInstanceIDs;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetVMInstanceRequiredIDs;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetVM;
export type schema = OperationStatusResponse;
export type schema = VirtualMachineScaleSetVMInstanceView;
export type schema = VirtualMachineScaleSetVMListResult;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
export type schema = OperationStatusResponse;
